### ISSUE TITLE
Slight texture issues on tooltip

### ISSUE THREAD

**Issue by mezz** [squeek502/AppleSkin#1]
Hovering over a food item, starting from the left and moving 1px right each screenshot:
On the third screenshot you can see some pink lines to the left of each saturation icon.

![2016-08-13_15 05 39](https://cloud.githubusercontent.com/assets/916092/17645898/80276aa6-6167-11e6-9271-78c6e0819984.png)
![2016-08-13_15 05 41](https://cloud.githubusercontent.com/assets/916092/17645900/802a2f20-6167-11e6-9da8-a422d54b946e.png)
![2016-08-13_15 05 43](https://cloud.githubusercontent.com/assets/916092/17645901/802a2e80-6167-11e6-996c-25f338be2538.png)
![2016-08-13_15 05 45](https://cloud.githubusercontent.com/assets/916092/17645899/8027ff5c-6167-11e6-879d-1c4dc19bb6ba.png)

**Comment by squeek502** [comment]
This is something that popped up in 1.7.2 (the same code in 1.6.4 didn't have this issue) and I've never been able to figure out why it happens, although I haven't looked too deeply.

It seems to be related to drawing scaled icons. Relevant code:

https://github.com/squeek502/AppleSkin/blob/1.10.2/java/squeek/appleskin/client/TooltipOverlayHandler.java#L136-L162

**Comment by mezz** [comment]
I had a similar issue with scaled icons on the Forestry Beealyzer. I solved it by... not scaling icons. :(
My best guess is it's a UV issue, where the scaled icons UVs do not exactly hit the right icon in the texture map due to extremely tiny float rounding errors.
Maybe you could make a mini version of the saturation icon to use?

**Comment by squeek502** [comment]
Took your suggestion and added smaller versions of the icons. Fixed in v1.0.1: https://github.com/squeek502/AppleSkin/releases/tag/v1.0.1
