### ISSUE TITLE
How do I pr 1.17-fabric

### ISSUE THREAD

**Issue by Cjsah** [squeek502/AppleSkin#106]
I modified some code to support `1.17-snapshot` at [this](https://github.com/Cjsah/AppleSkin/tree/1.17-fabric)
It supported **20w20a - 1.17-pre4** now `May support some earlier versions, but I haven't tested it yet`
Which branch should I pr to?

**Comment by squeek502** [comment]
Created a 1.17-fabric branch here: https://github.com/squeek502/AppleSkin/tree/1.17-fabric

**Comment by Cjsah** [comment]
> Created a 1.17-fabric branch here: https://github.com/squeek502/AppleSkin/tree/1.17-fabric

Okay, thanks, I pull requets my code
