### ISSUE TITLE
Avast Security moved apple skin to virus chest.

### ISSUE THREAD

**Issue by ShiguyA09** [squeek502/AppleSkin#107]
So i was running a security scan and it finds apple skin as a virus: Java:Malware are you trying to break my pc?

**Comment by squeek502** [comment]
Not sure what would cause this, seen it reported on CurseForge as well.

You're always welcome to inspect the source code, build the mod from source yourself, and/or decompile the distributed jar to confirm it matches the source code in the repository.

**Comment by squeek502** [comment]
Relevant thread about Optifine: https://www.reddit.com/r/Minecraft/comments/nba6im/avast_blocks_optifine_and_identifies_it_as_threat/

**Comment by squeek502** [comment]
Closing, not sure what happened but there's not much that can be done on AppleSkin's end AFAIK.
