### ISSUE TITLE
crash on startup fabric 1.17

### ISSUE THREAD

**Issue by TheNimbleNinja** [squeek502/AppleSkin#118]
https://gist.github.com/TheNimbleNinja/6363877105beea75712af463f4dad1b2

**Comment by squeek502** [comment]
Not sure how this is possible. In AppleSkin's entrypoint:

https://github.com/squeek502/AppleSkin/blob/ef43c983c2dc849ae9d86b201e8ee1a4bea290d4/java/squeek/appleskin/AppleSkin.java#L12

which sets `INSTANCE`:

https://github.com/squeek502/AppleSkin/blob/ef43c983c2dc849ae9d86b201e8ee1a4bea290d4/java/squeek/appleskin/ModConfig.java#L21

I guess that `getConfig` call is returning null?

**Comment by squeek502** [comment]
Maybe try deleting your `config/appleskin.json5` file and allow it to regenerate?

**Comment by SAGESSE-CN** [comment]
look like some mods call the item tooltip on construct phase, maybe we need add some security checks

**Comment by TheNimbleNinja** [comment]
i did delete all my configs and it still crashed

**Comment by squeek502** [comment]
Please try with v2.1.0. I believe this should be fixed now.

**Comment by squeek502** [comment]
Closing, please re-open if this has not been fixed.

**Comment by TheNimbleNinja** [comment]
im pretty sure this was fixed :)
