### ISSUE TITLE
Hide saturation/regen overlays when food can't be eaten.

### ISSUE THREAD

**Issue by Horse-5-333** [squeek502/AppleSkin#119]
The flashing yellow is annoying when food is in the offhand and it can't be eaten. I still want to know how many hunger points/health it grants when it can be eaten, but that info is useless when it cant be eaten.

**Comment by Horse-5-333** [comment]
I understand that this might not be worth it to implement considering the size of the request when you have other things to do.

**Comment by squeek502** [comment]
This makes sense. Goes hand-in-hand with how the health stuff works.

**Comment by SAGESSE-CN** [comment]
does "inedible" is food level is greater than equal to 20?

**Comment by squeek502** [comment]
> does "inedible" is food level is greater than equal to 20?

Yes, but should still display if `FoodComponent.isAlwaysEdible()` is true.

**Comment by squeek502** [comment]
This is what Minecraft uses in `Item.use`, we should do the same thing:

```java
if (player.canConsume(item.getFoodComponent().isAlwaysEdible())) {

}
```
