### ISSUE TITLE
foods with no hunger/saturation should be ignored

### ISSUE THREAD

**Issue by ghost** [squeek502/AppleSkin#121]
forge: 36.1.17
MC: 1.16.5
AppleSkin: 1.16.4-2.0.0

Some foods, like the vault burger and oozing pizza from the Vault Hunters mod, actually have 0 hunger/saturation

This causes a blank line and a faint black hunger honch to be drawn.  Foods with no food values should be ignored

https://imgur.com/a/Esl3fnD

**Comment by squeek502** [comment]
This should already be the case:

https://github.com/squeek502/AppleSkin/blob/86d0eef9d6ea9f0bb73ecfb25e9ee0df48857263/java/squeek/appleskin/client/TooltipOverlayHandler.java#L178-L186

Will need to look into what's happening more.

**Comment by ghost** [comment]
is it because of line 138 ?  the max being set to 1?

https://github.com/squeek502/AppleSkin/blob/86d0eef9d6ea9f0bb73ecfb25e9ee0df48857263/java/squeek/appleskin/client/TooltipOverlayHandler.java#L138

**Comment by squeek502** [comment]
Good catch, that's definitely it.

Note to self: it also seems weird to evaluate hunger and saturation rendering separately. If one is rendered, both should be I think (and vice versa; if one is not rendered, neither should be).

**Comment by ghost** [comment]
but sometime, someplace, somewhere there'll be occasion where a food has hunger and no sat, and vice versa? maybe?

**Comment by squeek502** [comment]
- 0 hunger and non-zero saturation is impossible, since saturation is calculated via `food.hunger * food.saturationModifier`.
- Non-zero hunger and 0 saturation is possible, but it would be better to render `0x <saturation icon>` than not render saturation at all (should be easy to extend our current 'large saturation' text rendering to handle the zero case)

**Comment by SAGESSE-CN** [comment]
@squeek502 Could `food. saturationModifier` be a negative number?

**Comment by squeek502** [comment]
Yes, AppleSkin should already negative saturation. See https://github.com/squeek502/AppleSkin/issues/35 and https://github.com/joshiejack/Mariculture/issues/125.
