### ISSUE TITLE
[1.16.5 Forge] Food tooltip not showing up in recipe book

### ISSUE THREAD

**Issue by ocram9** [squeek502/AppleSkin#129]
The tooltip for hunger/saturation will show up fine in the player inventory or in JEI but not in the recipe book. It's just empty space.

#### Screenshot:
![Screenshot_56](https://user-images.githubusercontent.com/49008532/126559080-88e49d58-19fe-4091-aeaa-cc8080eb2745.png)

#### Versions: 
- Forge 36.1.65
- Appleskin-forge-mc1.16.x-2.1.0
- Minecraft 1.16.5

**Comment by squeek502** [comment]
This is actually a Forge bug.

`RenderTooltipEvent.PostText` has an empty ItemStack because `RecipeBookGui`'s tooltip rendering methods are not hooked by Forge (`GuiUtils.preItemToolTip` and `GuiUtils.postItemToolTip` need to be called).

**Comment by squeek502** [comment]
Should be fixed in v2.2.0

EDIT: Fixed in Minecraft 1.17.1 at least, this would still need a fix in Forge for 1.16 which probably isn't going to happen.
