### ISSUE TITLE
Bewitchment vampire compat

### ISSUE THREAD

**Issue by VoidLock92** [squeek502/AppleSkin#133]
Right now appleskin-fabric-mc1.16.x-2.1.0 is causing hunger overlay to layer on top of the blood pips from Bewitchment. I am wondering if it is possible to get compatibility so that if a player becomes a vampire the hunger bar will disappear.

![image](https://user-images.githubusercontent.com/21327041/127259630-785f33c7-17f1-4534-8538-e816bc8a337e.png)

**Comment by VoidLock92** [comment]
Hemia has the same issue also. I do realize however that players can toggle the overlay off in the menu. Not sure if it is possible though to add support to recognize they are non human and toggle them off.

**Comment by squeek502** [comment]
There's now an API that those mods can use to add compatibility with AppleSkin: https://github.com/squeek502/AppleSkin/tree/1.16-fabric#for-mod-developers

Relevant issue: https://github.com/squeek502/AppleSkin/issues/94

**Comment by VoidLock92** [comment]
Awesome! I will report it on their GitHubs and let them know. Hopefully they can add support, that would be awesome. Thanks for the quick reply. Also thanks for an awesome mod!

**Comment by squeek502** [comment]
Looks like this was done by Bewitchment:

- https://github.com/MoriyaShiine/bewitchment/issues/172
- https://github.com/MoriyaShiine/bewitchment/commit/43b9d6f6a803989e901dc715557e2261daffcb1a
