### ISSUE TITLE
[Fabric] Latest REI broke AppleSkin integration

### ISSUE THREAD

**Issue by Desempregago** [squeek502/AppleSkin#134]
[Crash Report](https://pastebin.com/r2S7fqdm)
 
Minecraft 1.17.1
REI 6.0.266-alpha
AppleSkin 2.1.1

**Comment by squeek502** [comment]
Looks like `renderTooltipInner` got split into Fabric/Forge versions. Here's where the new Fabric version lives:

https://github.com/shedaniel/RoughlyEnoughItems/blob/6021d6e84f4609a98b823c507848d44e8eba078b/fabric/src/main/java/me/shedaniel/rei/impl/client/gui/fabric/ScreenOverlayImplImpl.java#L41

The fix might be as simple as updating the target class and the method signature in [AppleSkin's mixin](https://github.com/squeek502/AppleSkin/blob/1.17-fabric/java/squeek/appleskin/mixin/REITooltipMixin.java).

**Comment by Desempregago** [comment]
Glad to know it's a simple fix

**Comment by squeek502** [comment]
Thanks for reporting the issue. Should be fixed in v2.1.2.
