### ISSUE TITLE
REI Mixin Crash (fabric)

### ISSUE THREAD

**Issue by lazynessmind** [squeek502/AppleSkin#139]
### Bug

When loading minecraft, this mod is trying to mixin **me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl** and its failing.

**Mixin:** apple.mixins.json:REITooltipMixin

### Log:
[latest.log](https://github.com/squeek502/AppleSkin/files/6986358/latest.log)

### Versions:
REI Version: 6.0.268
AppleSkin Version: 1.17-2.1.1

**Comment by squeek502** [comment]
Update your AppleSkin, this has been fixed (duplicate of #134).
