### ISSUE TITLE
1.12.1 World Creation Crash

### ISSUE THREAD

**Issue by davqvist** [squeek502/AppleSkin#14]
AppleCore 2.2.2
AppleSkin 1.0.7
MC 1.12.1
Forge 2446

I decided to try if my modpack works in 1.12.1 as basically nothing has changed but I got the following crash when trying to make a new world,

https://pastebin.com/hLqsZmiT

**Comment by squeek502** [comment]
Will need to release a new version specifically targetting 1.12.1. Core mods are restricted to a single MC version, so the 1.12 version will not work with 1.12.1.

**Comment by squeek502** [comment]
Oh, wait, this is on the AppleSkin repo. This is an AppleCore-related crash and my previous comment was about AppleCore.

**Comment by squeek502** [comment]
This should be fixed once you update AppleCore to the new 1.12.1 version:
https://github.com/squeek502/AppleCore/releases/tag/v2.2.2
https://minecraft.curseforge.com/projects/applecore/files

**Comment by davqvist** [comment]
Thanks very much.
