### ISSUE TITLE
Saturation on F3 Menu

### ISSUE THREAD

**Issue by ActualBest** [squeek502/AppleSkin#142]
In the description, it says

> Adds hunger/saturation/exhaustion info to the debug overlay (F3)

Where is this added? I can't find it anywhere.

![2021-09-29_18 09 35](https://user-images.githubusercontent.com/78813556/135365109-1e7803d1-e587-4c0f-8f1f-b6ef6970a691.png)

**Comment by squeek502** [comment]
This is a Forge-only feature as of now.

**Comment by ActualBest** [comment]
Ok, good to know 👍

**Comment by squeek502** [comment]
Implemented in v2.2.0
