### ISSUE TITLE
[1.17.1-Forge] Food tooltip broke in recent forge versions due to the "tooltip" rewrite.

### ISSUE THREAD

**Issue by Gbergz** [squeek502/AppleSkin#146]
Title^ 

**MC**: 1.17.1
**Forge**: 37.0.97
**Apple Skin**: 2.1.0 | https://www.curseforge.com/minecraft/mc-mods/appleskin/files/3401359

**Screenshot**:
![image](https://user-images.githubusercontent.com/26634554/138122662-6d3571f8-66ca-468f-a77e-13b2225c8670.png)

Thanks,
**-** Gbergz

**Comment by squeek502** [comment]
Relevant PR: https://github.com/MinecraftForge/MinecraftForge/pull/8038
Relevant test/example code: https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/src/test/java/net/minecraftforge/debug/client/CustomTooltipTest.java

**Comment by SAGESSE-CN** [comment]
@squeek502 I'm sorry to bother your, we maybe needs release this fix first, players of 1.17.1 Forge are upgrading to the latest Forge.

I see some players report on the forums with the same issue. (from MCBBS/MCMOD)

**Comment by squeek502** [comment]
Fixed in v2.2.0
