### ISSUE TITLE
Regeneration amplifier divide by zero crash

### ISSUE THREAD

**Issue by teoWei** [squeek502/AppleSkin#148]
https://pastebin.com/dz2TYafy

**Comment by SAGESSE-CN** [comment]
Thank you for your feedback, what items are you holding in hand? 

It looks like [getAmplifier](https://github.com/squeek502/AppleSkin/blob/0ded2aebf63b6b71a64d3bbaf3fbc8df077ddbae/java/squeek/appleskin/helpers/FoodHelper.java#L103) is a big value

**Comment by teoWei** [comment]
It's a creative apple from the 1.17.1 fabric apple & carrot mod.

**Comment by SAGESSE-CN** [comment]
The [creative apple](https://github.com/agorasim20/ApplesCarrots/blob/c9d878662929e596a5bd2d52483eda7375bd17de/src/main/java/agorasim20/apples/apples/Apples.java#L16) amplifier is 9(level 10).

When amplifier is greater than 5(level 6), the effect is same to level 6, that each tick (non-game tick) to restore 1 health (0.5 heart).

**Comment by teoWei** [comment]
I don't know if this was involved in the crash but I was also using a mod that compacts the health bar if there's over 10 hearts.
It's Health Overlay (Fabric).

**Comment by SAGESSE-CN** [comment]
I'm pretty sure #149 has fixed it, and now just need to wait for merging
