### ISSUE TITLE
Appleskin fails to load correctly 

### ISSUE THREAD

**Issue by honeydbee** [squeek502/AppleSkin#154]
![image](https://user-images.githubusercontent.com/93289623/139142478-5a936a8a-bfb6-4e82-8a23-92e66a281641.png)
everytime i load up the game this shows up, i've removed the mod and i've redownloaded it but this continues to happen

**Comment by squeek502** [comment]
Try deleting the AppleSkin config file.

**Comment by honeydbee** [comment]
ah so sorry, but where do I find that?

**Comment by squeek502** [comment]
`config/appleskin-client.toml` in your Minecraft instance folder.

**Comment by squeek502** [comment]
Closing, can't do anything unless more info is provided.
