### ISSUE TITLE
Release on modrinth.com

### ISSUE THREAD

**Issue by CodeF53** [squeek502/AppleSkin#161]
Modrinth is an alternative to curseforge which is way better in a few key aspects:
  -  Proper filtering
     - on curseforge you can search for 1.17 mods, or fabric mods, not 1.17 fabric mods
     - it also has client/server mod filters
  -  Fast searches
     -  It takes nanoseconds for the search results to update to what you have typed, as opposed to the 3-5 seconds curseforge does
  - Easier API integration
     - Well documented, easy to use api
     - You can ask for support from actual humans

Along with this, there are a bunch of people who would like to use your mod, but won't go to curseforge to get it.

**Comment by squeek502** [comment]
Thanks for the heads up, I don't keep track of the modding community much anymore.

Page should be here once it's approved: https://modrinth.com/mod/appleskin
