### ISSUE TITLE
odd probably edge-case server sync scenario

### ISSUE THREAD

**Issue by superon** [squeek502/AppleSkin#164]
this is kinda hard to test to see what's really going on, also i'm not great at really seeing what's going on but here's my experience.

appleskin-fabric-mc1.16.x-2.1.3
fabric-api-0.42.0+1.16
loader version 0.11.6

so, when i load the game and connect to the smp the hung/sat value will not appear on food that i've added.
also the eating animation will not show but the food is still edible (just have to hold right mouse button for a second to eat the item, at which point the item will be eaten and a single "crunch" eating sound will be heard)
it appears fine in sp, and indeed if i connect to sp them smp it's also fine, hung/sat values, animation and all..
i've yet to be able to test this fully with another player but so far i've seen and heard they're also not seeing food values in the tooltips and not seeing the animation when eating as i'm also not seeing their eating animation when they're eating (or sound).

nothing mention in latest log or console about this afaik.

**Comment by squeek502** [comment]
What do you mean 'food that you've added'? Most likely you'll need the client to know about your added food as well, but what that exactly entails depends on how you've added food.

**Comment by superon** [comment]
i mean added with gourmet, i should forward this to DeltaNedas?

**Comment by deltanedas** [comment]
yeah this is definitely a gourmet issue, close

i have no idea how to do network stuff so its not suitable for server stuff yet
