### ISSUE TITLE
Please add display compatibility

### ISSUE THREAD

**Issue by xz123456xz** [squeek502/AppleSkin#166]
Please add Compatibility with Tough As Nails.

Show drinking water. Thank you~~

URL: https://www.curseforge.com/minecraft/mc-mods/tough-as-nails

**Comment by squeek502** [comment]
This is something that I'd prefer Tough As Nails to add themselves if they want it (or for a separate mod to implement). There's nothing special about AppleSkin that would make this easier to implement on our end.
