### ISSUE TITLE
Add a method for resource packs to integrate

### ISSUE THREAD

**Issue by sybenx** [squeek502/AppleSkin#167]
The yellow saturation meter does not match the shape of the hunger bar in some texture packs. I'm unaware of simple integration without editing the appleskin jar.

**Comment by squeek502** [comment]
You should be able to make a resource pack that includes a custom [`assets/appleskin/textures/icons.png`](https://github.com/squeek502/AppleSkin/blob/1.16-forge/resources/assets/appleskin/textures/icons.png)

**Comment by sybenx** [comment]
that worked. i looked before creating an issue and couldn't find any documentation on that. 

thanks
