### ISSUE TITLE
Consider using mod_version instead of combined version for fabric jars

### ISSUE THREAD

**Issue by clarfonthey** [squeek502/AppleSkin#170]
Whenever I load up appleskin via fabric, I get this warning:

```
[21:00:09] [main/WARN]: Mod `appleskin` (mc1.17.1-2.2.0) does not respect SemVer - comparison support is limited.
```

Ideally, the `fabric.mod.json` should be modified to use something semver compatible, which means either replacing `"version": "${version}"` with `"version": "${mod_version}"` or providing a "flipped" version string for Fabric like `2.2.0-mc1.17.1`.

Personally, I would use `${mod_version}` as the version string and additionally constrain the Minecraft version directly in the Fabric dependencies, adding: `"minecraft": ">=${minecraft_version}"` to the `"depends"` map.

Am willing to help provide specific PRs for this, but not sure what branches would be appropriate to send to, since the forge and fabric code is kept in separate branches, and I'm not sure what's maintained.

**Comment by squeek502** [comment]
Warning should be gone in v2.3.0.
