### ISSUE TITLE
Bug: Index -2 out of bounds for length 10

### ISSUE THREAD

**Issue by DEMEMZEA** [squeek502/AppleSkin#176]
The entire game crashes when i have a negative amount of hunger.

**Comment by SAGESSE-CN** [comment]
>  i have a negative amount of hunger.

How did you do it?

**Comment by DEMEMZEA** [comment]
> How did you do it?

https://www.spigotmc.org/resources/expandedenchants.98780/ ( as of its update 1.4, i don't know if this happens in 1.4.1 ) ( there is one thing there that can make your hunger negative )
