### ISSUE TITLE
Modrinth version?

### ISSUE THREAD

**Issue by clarfonthey** [squeek502/AppleSkin#183]
Right now the modrinth page doesn't include 2.4.0, so, I'm not sure if you plan to actively keep it up to date or not. Would be helpful if you could link it in the README and clarify whether you intend to keep it up to date, or whether we need to rely on CurseForge for proper updates.

**Comment by squeek502** [comment]
Whoops, forgot about this. Updated: https://modrinth.com/mod/appleskin
