### ISSUE TITLE
Feature suggestion: Add config to disable AS' additions to inventory hover tooltips

### ISSUE THREAD

**Issue by twome** [squeek502/AppleSkin#187]
Inspecio has a very nice & concise food info visualisation it adds to food tooltips, whereas AS' is a bit broken for me (at least with Inspecio and WTHIT installed) - AS renders each property of food on a separate line in the tooltips, rather than blending/overlaying them into a single icon. I'd love to be able to just choose Inspecio's tooltips and leave AS to exclusively deal with the HUD.

Thanks for the great mod!

**Comment by squeek502** [comment]
This is already an option in the config.
