### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gitdrug** [squeek502/AppleSkin#191]
.

**Comment by squeek502** [comment]
If I understand what you're requesting, AppleSkin does this where possible, but there are AppleSkin-specific icons that we need to use our own sprite sheet for.

EDIT: Worth noting you can provide a custom [`assets/appleskin/textures/icons.png`](https://github.com/squeek502/AppleSkin/blob/1.16-forge/resources/assets/appleskin/textures/icons.png) in a texture pack.
