### ISSUE TITLE
Personalized textures size

### ISSUE THREAD

**Issue by teidova** [squeek502/AppleSkin#195]
Having a 16x16 saturation texture over a 32x32 food texture is really ugly, but the icons.png file only includes 16x16 textures =(

Is there a way to put bigger textures ?

![image](https://user-images.githubusercontent.com/52156842/179289140-80939383-2bc3-4bce-b978-0793a21cf214.png)

**Comment by squeek502** [comment]
I believe all you need to do is create a bigger icons.png file (double the width and height) and it'll just work.

**Comment by squeek502** [comment]
Closing, please comment if this didn't work for you.
