### ISSUE TITLE
Idek what this means...

### ISSUE THREAD

**Issue by NotCharlieEver** [squeek502/AppleSkin#196]
I'm so confused what does this mean? I already am using fabric to launch it, I even tried copying fabric to the mods folder but it still shows this:
![image](https://user-images.githubusercontent.com/109411717/179346978-0e631038-a5c3-4716-970a-4bb831a2380f.png)

**Comment by squeek502** [comment]
You need Fabric API: https://www.curseforge.com/minecraft/mc-mods/fabric-api
