### ISSUE TITLE
Can't see saturation bar

### ISSUE THREAD

**Issue by Oyssis** [squeek502/AppleSkin#197]
I cannot see the saturation bar and its on in modmenu

**Comment by squeek502** [comment]
Are you playing on a multiplayer server? If so, is AppleSkin installed on the server?

**Comment by Oyssis** [comment]
No its not installed on the server but its supposed to work

**Comment by squeek502** [comment]
> its supposed to work

It only fully works if it's installed on the server. From the description on CurseForge:

> This is a mostly client-side mod, but it needs to be on the server in order to display accurate saturation/exhaustion values on the client.

**Comment by Oyssis** [comment]
No it compeletly doesnt work I remember it worked..

**Comment by squeek502** [comment]
You're going to have to give me more info. I can't fix something that I can't reproduce.

Does it work for you in single player? Do you have any other mods installed? Does it work if you only have AppleSkin installed? How are you determining that it "doesn't work"?

**Comment by squeek502** [comment]
Assuming this is not a bug unless more info is given.

**Comment by Oyssis** [comment]
Yeah I can't give you more infromation on what happend there for some time it somehow works now the only thing I can think of is it might be a multiconnect bug but it works now so
