### ISSUE TITLE
error in the client

### ISSUE THREAD

**Issue by h4che404** [squeek502/AppleSkin#198]
![image](https://user-images.githubusercontent.com/108189589/182963142-84c4e34b-5f86-4f6c-b788-719d9e6f3b73.png)
Hi, I have this error in my minecraft 1.19, how can I fix it?
And I have to add the same file to the server?

**Comment by GirafiStudios** [comment]
Make sure you´re on the latest Apple Skin and Minecraft Forge version for 1.19

Apple Skin is required on the server, for the saturation overlay to work. But the tooltip for food values on food, will still shows if it´s only on the client.

**Comment by squeek502** [comment]
What @GirafiStudios said. Update Forge and/or AppleSkin.

**Comment by squeek502** [comment]
This actually looks to be the same error as https://github.com/squeek502/AppleSkin/issues/192#issuecomment-1182222808. So updating to AppleSkin v2.4.2 should fix it.
