### ISSUE TITLE
[Not sure if bug] Mod requires Apple Core

### ISSUE THREAD

**Issue by DarkLight66** [squeek502/AppleSkin#2]
Not sure if it's supposed to, since it kind of defeats the purpose of this being a different mod rather than being part of Apple Core, and curseforge doesn't show Apple Core as a required library.

**Comment by squeek502** [comment]
AppleCore is not required, but if AppleCore _is_ installed along with AppleSkin, then there is a minimum required version of AppleCore (2.0.0). This is because if AppleCore < 2.0.0 was used with AppleSkin, the HUD features of each would conflict with eachother.

**Comment by DarkLight66** [comment]
Wow i didn't realize i had an older version of Apple Core, i feel dumb now, thanks anyways.

**Comment by squeek502** [comment]
No worries. :smile:
