### ISSUE TITLE
[1.18.2] AppleSkin failed to recognize dynamic food

### ISSUE THREAD

**Issue by khjxiaogu** [squeek502/AppleSkin#201]
In 1.18, forge added a method in item `getFoodProperties(ItemStack)` this allows foods have dynamic food properties. However, Apple Skin uses the method that is not itemstack sensitive. This cause the value display incorrect.
Related: TeammoegMC/Caupona#20

**Comment by squeek502** [comment]
Note to self: this was added in Forge 40.0.47

**Comment by SAGESSE-CN** [comment]
Are you going to do it yourself :p

**Comment by squeek502** [comment]
The changes [were already made in 1.19 version](https://github.com/squeek502/AppleSkin/commit/0030c262b264ffff40fd09ab832db0a8ff2c72e1), just need to backport them to 1.18.2. Working on it now.

**Comment by SAGESSE-CN** [comment]
Maybe we should use `ItemStack.getFoodProperties`

**Comment by squeek502** [comment]
Should be fixed in [`appleskin-forge-mc1.18.2-2.4.1`](https://www.curseforge.com/minecraft/mc-mods/appleskin/files/3927564)
