### ISSUE TITLE
[1.18.2 Forge] Incompatible with Enigmatic Legacy

### ISSUE THREAD

**Issue by Reshy** [squeek502/AppleSkin#202]
https://pastebin.com/5xvM26J0

**Comment by SAGESSE-CN** [comment]
the worst thing happened. some mods mixin [TooltipOverlayHandler](https://github.com/Aizistral-Studios/Enigmatic-Legacy/blob/1.18.X/src/main/java/com/integral/enigmaticlegacy/mixin/MixinTooltipOverlayHandler.java).

**Comment by squeek502** [comment]
[Enigmatic-Legacy](https://github.com/Aizistral-Studios/Enigmatic-Legacy) will need to update their mixin, or better yet, use [squeek.appleskin.api.event.TooltipOverlayEvent](https://github.com/squeek502/AppleSkin/blob/1.18-forge/java/squeek/appleskin/api/event/TooltipOverlayEvent.java)

**Comment by squeek502** [comment]
Added proper instructions for how to use the AppleSkin API with Forge: https://github.com/squeek502/AppleSkin#for-mod-developers

**Comment by INooBTooMuch** [comment]
> [Enigmatic-Legacy](https://github.com/Aizistral-Studios/Enigmatic-Legacy) will need to update their mixin, or better yet, use [squeek.appleskin.api.event.TooltipOverlayEvent](https://github.com/squeek502/AppleSkin/blob/1.18-forge/java/squeek/appleskin/api/event/TooltipOverlayEvent.java)

Is [this](https://gist.github.com/INooBTooMuch/81aa67f9754bb56630306432111846cf) the same issue, I do have Enigmatic Legacy installed and this error showed up today and just wondering if I need to make a new issue to prevent posting the same thing

**Comment by squeek502** [comment]
> Is [this](https://gist.github.com/INooBTooMuch/81aa67f9754bb56630306432111846cf) the same issue

Yep, same problem.

**Comment by itsdinkd** [comment]
Enigmatic hasn't updated in 3 months though so wouldn't it be Apple Skin that needs to fix?

**Comment by INooBTooMuch** [comment]
Based on a recent update this should be fixed, I haven't had the chance to try it out though.
