### ISSUE TITLE
[1.18.2 Forge] I'm having a weird issue

### ISSUE THREAD

**Issue by INooBTooMuch** [squeek502/AppleSkin#206]
I have been freezing while either creating a new world in the loading screen or joining an old world right after moving.
The only way to close minecraft after the freezing is to "End task" on the "Openjdk platform binary" in task manager since alt+f4 doesn't work.
I can't read Log files so I try to troubleshoot manually by disabling mods and playing, but it is not stable (let me explain):

(For today at least)
• The first try was to disable:
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
Apple Skin
[Champions](https://www.curseforge.com/minecraft/mc-mods/champions)
[Origins: Classes (Forge)](https://www.curseforge.com/minecraft/mc-mods/origins-classes-forge)
[Scaling Health](https://www.curseforge.com/minecraft/mc-mods/scaling-health)
[Silent Lib (silentlib)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)

(I was lead to this by troubleshooting yesterday too but I didn't keep what mods I had disabled so there might be more)
The first try it was ok and the game loaded but froze when exiting (had to close by Task Manager)

• Second try I disabled:
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Champions](https://www.curseforge.com/minecraft/mc-mods/champions)
[Origins: Classes (Forge)](https://www.curseforge.com/minecraft/mc-mods/origins-classes-forge)
[Scaling Health](https://www.curseforge.com/minecraft/mc-mods/scaling-health)
[Silent Lib (silentlib)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)
And Enabled Apple Skin

It lead to a crash in the loading screen.

• Third Try was to retry the first one and it crashed again.

Also I have Enigmatic Legacy so I had to play with the previous version of Apple Skin (appleskin-forge-mc1.18-2.4.0.jar)

[First Log](https://gist.github.com/INooBTooMuch/0e898548e96d3832870b7290370c6d6e)
[Second Log](https://gist.github.com/INooBTooMuch/7bdf5b8cdab598ba1835de4f91f7b6d3)
[Third Log](https://gist.github.com/INooBTooMuch/b44f18ec193b93c2ba97d11854d1b2aa)

Versions :
Minecraft : 1.18.2
Apple Skin : 1.18-2.4.0
Forge : 40.1.73

I tried deleting the .minecraft folder as said in a couple of videos but it didn't work.
If the problem is not caused by Apple Skin I'm sorry but I can't figure out what it is, If the log files help pls tell me which mod it is so that I can test.
Also if the problem is caused because I am playing on the previous version of Apple Skin I guess I'll have to wait for the problem with Enigmatic Legacy to be solved.

**Comment by squeek502** [comment]
- Is the crash consistent?
- If you *only* remove AppleSkin, does the crash stop happening?

**Comment by INooBTooMuch** [comment]
I just tested it without Apple Skin and it still crashed, I don't know what is happening sorry.
