### ISSUE TITLE
Dehydration Support

### ISSUE THREAD

**Issue by ardissaps** [squeek502/AppleSkin#210]
Would you please add [Dehydration ](https://www.curseforge.com/minecraft/mc-mods/dehydration)icon to the tooltip to show how many it will replenish? thx
![image](https://user-images.githubusercontent.com/82106625/188116781-96a9d104-e551-404c-81d8-ce42cb6d528f.png)

**Comment by squeek502** [comment]
No plans for this. Someone else can make a separate mod for this (like [this](https://www.curseforge.com/minecraft/mc-mods/waterskin)) or support can be added to Dehydration itself if that's something they want to do.
