### ISSUE TITLE
Exhaustion underlay not showing

### ISSUE THREAD

**Issue by RevanMardagh** [squeek502/AppleSkin#215]
exhaustion underlay doesnt appear

**Comment by squeek502** [comment]
If you're playing on a server, AppleSkin must be installed on the server for exhaustion to show up.

If you're playing in single player, then more info is needed:

What version of Minecraft? Forge or Fabric? What version of AppleSkin? Does the problem still occur if you try running with *only* AppleSkin installed?

**Comment by RevanMardagh** [comment]
oh yes, i am on a server. thank you for your help
