### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by caracolito2-0** [squeek502/AppleSkin#217]
[crash-2022-12-03_19.02.40-client.txt](https://github.com/squeek502/AppleSkin/files/10147461/crash-2022-12-03_19.02.40-client.txt)

**Comment by squeek502** [comment]
On first glance, this doesn't look related to AppleSkin. The error is:

> Failed to load Force Resource Cache Configuration from C:\Users\mraba\curseforge\minecraft\Instances\Manuelito\config\forge-resource-caching.toml

Does the crash go away if you uninstall AppleSkin?

**Comment by caracolito2-0** [comment]
i reported this error to the Supplementaries mod developer (as their mod was failing too). he told me to delete their config files, didn't work, tried deleting AppleSkin's and Supplementaries'  config files, didn't work either, and then i deleted the entire config folder and it worked. some other file must have been corrupted, i don't know which one tho.

**Comment by squeek502** [comment]
According to the crash log, it was `config\forge-resource-caching.toml`
