### ISSUE TITLE
[Question] Multiplayer - vanilla server?

### ISSUE THREAD

**Issue by VariableVixen** [squeek502/AppleSkin#22]
The mod description says that
```
This is a mostly client-side mod, but it needs to be on the server in order to display accurate saturation/exhaustion values on the client.
```
I was wondering if that still holds true on a server that doesn't modify the hunger/saturation/exhaustion values of food. I have a spigot 1.12.2 server I run for my friends and I, and all of the food is still using purely vanilla values. Would this mod on a client still work and report the vanilla values in the absence of a server mod informing it of any changes?

**Comment by squeek502** [comment]
That description is only talking about the player's saturation/exhaustion values. All food values will be accurate no matter what.

**Comment by VariableVixen** [comment]
Ohh, okay! Thank you! Is there any way to get those values sent to the client from a spigot server, or would that require a port of the part of this mod?

**Comment by squeek502** [comment]
Not familiar with Spigot, but yeah it'd need something like this: https://github.com/squeek502/AppleSkin/tree/1.12/java/squeek/appleskin/network

IIRC the default Minecraft hunger packet could be re-used for the purpose of syncing saturation; you'd just need to make the server send it more often than it usually does (in vanilla, it only sends the packet when saturation hits zero or hunger changes). Exhaustion syncing would be harder to do with a purely server-side plugin, though, since there's no existing packet used for that in Minecraft.

**Comment by James-E-A** [comment]
Am I understanding this: right now, the client-side AppleSkin is _only_ an estimate of true values; it could drift some amount between packets?

> IIRC the default Minecraft hunger packet could be re-used for the purpose of syncing saturation; you'd just need to make the server send it more often than it usually does

> This is a mostly client-side mod, but **it needs to be on the server** in order to display accurate saturation/exhaustion values on the client.

So… _is_ there available a server-side plugin for this?

I see [this plugin](https://dev.bukkit.org/projects/paperapple), but it appears to be an unmaintained 3rd-party implementation.

**Comment by squeek502** [comment]
> the client-side AppleSkin is only an estimate of true values

Not really an estimate, it just shows the current values that the client has (which don't update on their own).

> So… is there available a server-side plugin for this?

Not sure. If that plugin does what it says, then it might work fine (i.e. install that on the server, and then load AppleSkin on the client).

**Comment by jmattingley23** [comment]
Digging up this old thread in case anyone else is interested in using this mod on paper/spigot servers - I've implemented the server-side component as a plugin here: https://github.com/jmattingley23/AppleSkinSpigot

**Comment by squeek502** [comment]
Thanks @jmattingley23, added a link to it in the description on Curseforge.
