### ISSUE TITLE
Incompatibility with autofish

### ISSUE THREAD

**Issue by g3ryll** [squeek502/AppleSkin#224]
I am trying to use appleskin for fabric 19.3 and it's crashing.
This is the crash report file:
[crash-2023-02-03_14.23.18-client.txt](https://github.com/squeek502/AppleSkin/files/10579797/crash-2023-02-03_14.23.18-client.txt)

**Comment by squeek502** [comment]
Looks like the same crash as https://github.com/squeek502/AppleSkin/issues/221

The `autofish` mod seems to be incompatible with AppleSkin
