### ISSUE TITLE
Mark Modrinth Versions as Quilt-compatible

### ISSUE THREAD

**Issue by sylv256** [squeek502/AppleSkin#226]
![AppleSkin 2.4.2 on MC 1.19.3 for Fabric](https://user-images.githubusercontent.com/18603248/221378008-f8705a79-1c2e-46d5-b0d1-c1e517e942df.png)
The Fabric versions of AppleSkin are compatible with Quilt. It would be nice to be able to search for Quilt-compatible mods and AppleSkin to show up.

**Comment by squeek502** [comment]
Done, thanks for letting me know it works.
