### ISSUE TITLE
Suggestion: Style Config Option

### ISSUE THREAD

**Issue by IdrisQe** [squeek502/AppleSkin#23]
This mod is such a boon to quality of life; I can't begin to say just how useful it is.
One thing has always bothered me a bit though: The appearance of the tooltip.
Rather than seamlessly integrating into the tooltip, it instead adds a grey box on the bottom. In comparison to mods that do similar things (Quark's Food Tooltip [which doesn't show saturation], Quark's Stat Display, the Tough As Nails AppleSkin addon) put the icons inside the tooltip of the item.

I know it's not a major issue, but as a person who has a very particular aesthetic sense and who likes things to fit in, I would really appreciate a config option at least to change the display to be more in-line with other such mods and fit in with the tooltips better in general.

I've included the Quark Food Tooltip image, and the AppleSkin Tough As Nails addon Hydration Tooltip image as reference for what I mean.

![image](https://user-images.githubusercontent.com/40530630/45883888-30a1ee80-bd67-11e8-8fae-23b534a045cc.png)

![image](https://user-images.githubusercontent.com/40530630/45883908-40b9ce00-bd67-11e8-993b-36559df0d5f1.png)

**Comment by squeek502** [comment]
Wasn't made a config option, but the default style is now the 'integrated into the tooltip' one in v2.0.0.
