### ISSUE TITLE
Crash when holding a gapple.

### ISSUE THREAD

**Issue by Taureon** [squeek502/AppleSkin#230]
How to replicate: Hold a golden apple
I don't know much info about it besides "i am holding a golden apple", but i hope this error log helps
![image](https://user-images.githubusercontent.com/45183108/230494107-9b7d06e6-47a0-4518-bd74-d1a239ac2840.png)

**Comment by squeek502** [comment]
What version of Minecraft? What version of AppleSkin? My guess is that you need to update your AppleSkin to better match the version of Minecraft you're using.

**Comment by Taureon** [comment]
i was using minecraft version 1.19.4 and the file name of the mod is "appleskin-fabric-mc1.19-2.4.1.jar" so it assume its version is 2.4.1

**Comment by Taureon** [comment]
or it may be related instead to something on the server that I was playing on, I just tested it on a singleplayer world (same mods as yesterday) to record a video and it didn't crash.
i guess this is why i shouldn't file bug reports at midnight, this should be closed.

**Comment by squeek502** [comment]
For 1.19.4 you need [appleskin-fabric-mc1.19.4-2.4.3.jar](https://www.curseforge.com/minecraft/mc-mods/appleskin/files/4440101)
