### ISSUE TITLE
Bitdefender detects Trojan in appleskin 2.4.1, fabric minecraft 1.19.2

### ISSUE THREAD

**Issue by KamilBeda** [squeek502/AppleSkin#234]
![image](https://user-images.githubusercontent.com/23322562/236045177-86e4a3ed-be68-47b4-a1d4-373657542901.png)

**Comment by squeek502** [comment]
This is a false positive. Don't think there's anything I can do on my end to resolve this.

You're always welcome to inspect the source code, build the mod from source yourself, and/or decompile the distributed jar to confirm it matches the source code in the repository.

**Comment by KamilBeda** [comment]
Malwarebytes marks file as safe so yeah, must be a false positive

**Comment by PajTajster** [comment]
Just wanted to add, yesterday I did scanned this particular version with VirustTotal, yielding 10 detections. Today it went down to 2:
https://www.virustotal.com/gui/file/956d21e619d13d4a064513c4a0d490c382795b8466c79d6db61431d8532ef461
Here's how it used to look like yesterday:
![image](https://user-images.githubusercontent.com/38697671/236461348-113b6edf-3afe-477c-8365-8514dd0895e5.png)

Perhaps vendors found out it's a false-positive and corrected it.

Maybe interesting, maybe not, next version (and any newer after that) has no detections whatsoever:
https://www.virustotal.com/gui/file/e71e9963e24f9a9b8f471709ae1340b0be3093d00c53e23687a638de9e925126?nocache=1

**Comment by squeek502** [comment]
Down to 1/61 now. Don't know what happened here, but going to consider this resolved.
