### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by gamerpotion** [squeek502/AppleSkin#236]
Hi for some reason Bitdefender is catching Appleskin as a virus. No other mod is doing this but Appleskin
Have tested downloading a fresh file and each time it does it.

![](https://media.discordapp.net/attachments/1003407908463190073/1103111337925677076/image.png)

![](https://media.discordapp.net/attachments/1003407908463190073/1103111549960343652/image.png?width=1093&height=245)

**Comment by squeek502** [comment]
Duplicate of https://github.com/squeek502/AppleSkin/issues/234

> This is a false positive. Don't think there's anything I can do on my end to resolve this.
>
> You're always welcome to inspect the source code, build the mod from source yourself, and/or decompile the distributed jar to confirm it matches the source code in the repository.

**Comment by gamerpotion** [comment]
Have removed from the modpack as unable to even download the mod before it gets quarantined. This is the first time ive seen a mod be flagged up like this with over 200+ mods downloaded in the past, very strange.
Sorry didnt realise a duplicate, but yeah have removed from modpack, so closing this thread.
