### ISSUE TITLE
Crash on 1.19.4 Fabric

### ISSUE THREAD

**Issue by FlameFire26** [squeek502/AppleSkin#237]
Fabric ver. 0.14.19, Fabric API ver. 0.81.1

Installed mods:
modmenu-6.2.2
appleskin-fabric-mc1.19.4-2.4.3

[crash-report-2023-5-18_1.11.26.zip](https://github.com/squeek502/AppleSkin/files/11500981/crash-report-2023-5-18_1.11.26.zip)

Downgrade Fabric to 0.14.18 and API 0.78.0, the peoblem remains.

**Comment by FlameFire26** [comment]
Java have tried JDK 17.0.3.1/18.0.2.1/19.0.2

**Comment by squeek502** [comment]
Can't reproduce this, everything seems to be working fine for me. Tried with:

- `appleskin-fabric-mc1.19.4-2.4.3`
- `fabric-api-0.81.1+1.19.4`
- `modmenu-6.2.2`
- Fabric Loader `v0.14.19`
- Java 17.0.2

**Comment by SAGESSE-CN** [comment]
SpongePowered MIXIN Subsystem Version=0.8.5

https://github.com/squeek502/AppleSkin/blob/d8413a827b8e02f9649f48d613190843b8195f75/java/squeek/appleskin/mixin/util/BeforeInc.java#L23

https://github.com/SpongePowered/Mixin/blob/155314e6e91465dad727e621a569906a410cd6f4/src/main/java/org/spongepowered/asm/mixin/injection/InjectionPoint.java#L787

**Comment by squeek502** [comment]
The crash says that `Mixin` can't find a constructor of `BeforeInc` that takes an `InjectionPointData`, but it does exist:

https://github.com/squeek502/AppleSkin/blob/d8413a827b8e02f9649f48d613190843b8195f75/java/squeek/appleskin/mixin/util/BeforeInc.java#L31-L37

so the crash log is confusing.

**Comment by FlameFire26** [comment]
I was using an integration package to test it. Maybe it's had do some changes to the game.
I download a new 1.19.4 to find that it has no problem.
Sorry for that.

**Comment by FlameFire26** [comment]
I know a little about Java language, but well, thx.



---Original---
From: "Ryan ***@***.***&gt;
Date: Thu, May 18, 2023 08:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [squeek502/AppleSkin] Crash on 1.19.4 Fabric (Issue #237)




 
A constructor that takes InjectionPointData also exists, though:
 
https://github.com/squeek502/AppleSkin/blob/d8413a827b8e02f9649f48d613190843b8195f75/java/squeek/appleskin/mixin/util/BeforeInc.java#L31-L37
