### ISSUE TITLE
The transparent texture shows on the hunger bar.

### ISSUE THREAD

**Issue by wret8385** [squeek502/AppleSkin#238]
<img width="136" alt="image" src="https://github.com/squeek502/AppleSkin/assets/87554209/ae05fecb-1c60-41f3-ae87-3c8af42a21f5">

**Comment by squeek502** [comment]
If you're circling the checkerboard pattern behind the hunger bar, that is intentional. It shows your exhaustion level. You can turn it off in the config if you don't want it.

**Comment by wret8385** [comment]
ok
