### ISSUE TITLE
Suggestion: Rift

### ISSUE THREAD

**Issue by Diamondman121314** [squeek502/AppleSkin#24]
I'm not sure if possible, but I see that this has been released for Fabric for 1.14. There's been a mod loader for 1.13(.2) called Rift, if you haven't heard of it. There's two versions currently though, the 1.13 by Runemoro and the 1.13.2 fork of it by Chocohead. I was possibly hoping that you could consider, if not already, porting to that.

**Comment by squeek502** [comment]
Yeah I was considering this. Will look into it more.

**Comment by squeek502** [comment]
Ended up deciding against this for now. Not sure of Rift's future and it's less documented than Fabric so it's a bit harder to jump in to.
