### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by SorkoPiko** [squeek502/AppleSkin#242]
Hello, could you please update the mod to 1.20? 1.20 is out, and this is one of my favourite mods. Thanks!

**Comment by squeek502** [comment]
Fabric version for Minecraft 1.20 released: https://github.com/squeek502/AppleSkin/releases/tag/v2.5.0

Having some trouble getting the 1.20 Forge MDK to work, will likely end up needing to wait for some examples from other mods to understand what needs to be done there (AFAICT there's no Forge 1.20 mods on CurseForge yet).

**Comment by SAJewers** [comment]
the 1.20 version for fabric doesn't work on quilt atm fyi. it requires fabricloader 0.14.21, but the latest version of quilt on available on prism launcher (0.19.0-beta.18) presents itself as 0.14.19

**Comment by SorkoPiko** [comment]
Thanks, I use fabric. Hope I didn't rush you!

**Comment by SAGESSE-CN** [comment]
> the 1.20 version for fabric doesn't work on quilt atm fyi. it requires fabricloader 0.14.21, but the latest version of quilt on available on prism launcher (0.19.0-beta.18) presents itself as 0.14.19

this is fabric hard requirements, we can't change it.

**Comment by SAJewers** [comment]
> the 1.20 version for fabric doesn't work on quilt atm fyi. it requires fabricloader 0.14.21, but the latest version of quilt on available on prism launcher (0.19.0-beta.18) presents itself as 0.14.19

Quilt just updated to support fabricloader 0.14.21, so appleskin now works on Quilt in 1.20
https://github.com/QuiltMC/quilt-loader/issues/316#issuecomment-1585864340

**Comment by squeek502** [comment]
Forge version released:
- https://legacy.curseforge.com/minecraft/mc-mods/appleskin/files/4605078
- https://github.com/squeek502/AppleSkin/releases/tag/v2.5.0
- https://modrinth.com/mod/appleskin/version/2.5.0+mc1.20.1
