### ISSUE TITLE
Forge 1.20 Request

### ISSUE THREAD

**Issue by Jaedn** [squeek502/AppleSkin#248]
If it wouldn't be too much trouble, I'd like to request a version compatible with Forge 1.20 (not 1.20.1). The old 1.19.4 version crashes and 1.20.1 is too new. Of course, if this cannot be achieved it is perfectly understandable.

**Comment by squeek502** [comment]
The Forge tooltip API didn't work in 1.20 (https://github.com/MinecraftForge/MinecraftForge/pull/9533), so there will be no Forge version of AppleSkin for 1.20.

**Comment by SAGESSE-CN** [comment]
forge won't update 1.20 again, so you can give it up.

**Comment by Jaedn** [comment]
> The Forge tooltip API didn't work in 1.20 (https://github.com/MinecraftForge/MinecraftForge/pull/9533), so there will be no Forge version of AppleSkin for 1.20.

Ah I see, thanks for the info
