### ISSUE TITLE
AppleSkin needs update to Fabric Loader 0.2.0.69+

### ISSUE THREAD

**Issue by asiekierka** [squeek502/AppleSkin#25]
I didn't realize that org.spongepowered.asm.lib is used by InjectionPoints, and I haven't realized someone already used them. As of 0.2.0.69, we use org.objectweb.asm globally.

PS. Could you make your injection point namespaced in some manner?

**Comment by asiekierka** [comment]
Though I'm not sure if we *should* be making Mixin use the global ASM library, for interop with Sponge...

**Comment by asiekierka** [comment]
Wait on this issue. I'll get back to you.

**Comment by asiekierka** [comment]
Contacted Sponge, reverting on our side

**Comment by squeek502** [comment]
Alright. Let me know if you still think its a good idea to namespace my `@InjectionPoint.AtCode`

**Comment by asiekierka** [comment]
It still is, yes, I think.

**Comment by squeek502** [comment]
Makes sense, will do. :+1:
