### ISSUE TITLE
The rendering of blocks seems to be broken after installing AppleSkin.

### ISSUE THREAD

**Issue by SCOS100** [squeek502/AppleSkin#251]
I wanted to install AppleSkin, after that the blocks started overlaying on each other? It's like a rendering issue that never happened to me.
For example:
If i place a block like grass and put a wall in front of it, i can still see the block even if there is a wall.
Any fix?

**Comment by squeek502** [comment]
What version of AppleSkin? What version of Minecraft? Forge or Fabric? Can you post a list of your mods?

Just to be sure, the problem goes away if you remove AppleSkin?

**Comment by SCOS100** [comment]
I used minecraft 1.12.2 and appleskin 0.14 on forge.
Also i had EnergyMeters, immersive engineering, jei, jec, jer and NuclearCraft

**Comment by SCOS100** [comment]
> What version of AppleSkin? What version of Minecraft? Forge or Fabric? Can you post a list of your mods?
> 
> Just to be sure, the problem goes away if you remove AppleSkin?

I used minecraft 1.12.2 and appleskin 0.14 on forge.
Also i had EnergyMeters, immersive engineering, jei, jec, jer and NuclearCraft.
I am sure that it worked before.

**Comment by squeek502** [comment]
Can't reproduce this with:

Forge 14.23.5.2860
AppleSkin-mc1.12-1.0.14.jar
energymeters-1.12.2-1.0.2.jar
ImmersiveEngineering-0.12-98.jar
jei_1.12.2-4.16.1.1003.jar
JustEnoughCalculation-1.12.2-3.2.7.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
NuclearCraft-2.18zzz-1.12.2.jar

![2023-07-17_20 52 24](https://github.com/squeek502/AppleSkin/assets/2389051/054249f1-3779-4890-a6b0-e47e6fc2409b)

Please provide a screenshot of the bug, and double check that removing AppleSkin makes the bug go away.

**Comment by SCOS100** [comment]
![Screenshot_2023-07-18-20-56-46-183_net kdt pojavlaunch-edit](https://github.com/squeek502/AppleSkin/assets/111370306/f07f0391-5e14-42ba-bbf9-b1aaf1e8ea0b)

Ok so, if you can't understand what's happening, i did exactly like you, and it seems like it also applies to mobs, and it's not because of OpenGL, because it never happened like i said in the title.

**Comment by squeek502** [comment]
Remove AppleSkin and check if that fixes it.

I can't do anything about this until:
- I know for sure that AppleSkin is the mod causing the problem
- I have a way to reproduce it on my end

**Comment by SCOS100** [comment]
it's not an appleskin problem, closing.
