### ISSUE TITLE
Incompatibility with raised

### ISSUE THREAD

**Issue by alba4k** [squeek502/AppleSkin#252]
![immagine](https://github.com/squeek502/AppleSkin/assets/84153269/482de738-40ee-4785-a603-d9f7b55a7fc0)

Changing the position of the food bar on screen seems to cause some weird behaivour

https://modrinth.com/mod/raised

**Comment by SkyTheNerd** [comment]
I had the same issue. If you are using raised 2.0.0, you have not downloaded the add-on file.

**Comment by alba4k** [comment]
Which add-on file?

**Comment by squeek502** [comment]
> Which add-on file?

I would assume the one with `appleskin` in the name, e.g. `raisedxappleskin-fabric-1.20.1-2.5.0.jar` from here:

https://modrinth.com/mod/raised/version/Fabric-1.20.1-2.0.0

**Comment by alba4k** [comment]
Yes, thanks a lot, that fixed it (it was 1.19.4 for my case, but that's not relevant)

Maybe this could be mentioned somewhere here or on modrinth/cf?
