### ISSUE TITLE
compatibility with fabric mods

### ISSUE THREAD

**Issue by Romawkawuwu** [squeek502/AppleSkin#253]
lots of users use "raised" mode, can you make compatibility with this tipe of mods 
![изображение](https://github.com/squeek502/AppleSkin/assets/139974203/747a9144-1e08-4fd4-ace7-0c2b1482061a)

**Comment by squeek502** [comment]
Download the appleskin addon for raised, see https://github.com/squeek502/AppleSkin/issues/252
