### ISSUE TITLE
AppleSkin's AutoConfig tooltips cannot be translated

### ISSUE THREAD

**Issue by Utopia1916** [squeek502/AppleSkin#256]
I placed the language JSON file in the assets-appleskin-lang directory of the resource pack, but only some of the text has an effect, while the rest has no effect at all. I'm quite certain that I saw these codes in the source code, and the GUI interface in the game is also displaying these words, but they just don't work. Why?
This is the part that doesn't work in the JSON:
{
  "Alpha value of the flashing icons at their most visible point (1.0 = 完全不透明，0.0 = 完全透明)": "闪烁图标在最可见时的透明度（1.0 = 完全不透明，0.0 = 完全透明）",
  "If true, shows the hunger and saturation values of food in its tooltip while holding SHIFT": "如果为true，在按住SHIFT键时，在悬浮提示中显示食物的饥饿和饱和度数值",
  "If true, shows the hunger and saturation values of food in its tooltip automatically (without needing to hold SHIFT)": "如果为true，自动在悬浮提示中显示食物的饥饿和饱和度数值（无需按住SHIFT键）",
  "If true, shows the hunger (and saturation if showSaturationHudOverlay is true) that would be restored by food you are currently holding": "如果为true，显示你当前手持食物能够恢复的饥饿值（如果[显示饱和度]也为true，则还会显示饱和度值）",
  "If true, enables the hunger/saturation/health overlays for food in your off-hand": "如果为true，在副手中也显示食物的饥饿/饱和度/生命",
  "If true, shows estimated health restored by food on the health bar": "如果为true，显示食物所能恢复的预计生命值覆盖在生命条上",
  "If true, shows your food exhaustion as a progress bar behind the hunger bar": "如果为true，显示食物耗尽进度作为进度条在饥饿条后面",
  "If true, shows your current saturation level overlayed on the hunger bar": "如果为true，在饥饿条上显示当前的饱和度水平",
  "If true, shows your hunger, saturation, and exhaustion level in Debug Screen": "如果为true，在调试屏幕显示你的饥饿、饱和度和耗尽等级",
  "If true, health/hunger overlay will shake to match Minecraft's icon animations": "如果为true，健康/饥饿覆盖将会与Minecraft的图标动画同步晃动"
}

**Comment by squeek502** [comment]
Looks like we use `@Comment` which doesn't integrate with lang files:

https://shedaniel.gitbook.io/cloth-config/auto-config/annotations#special-case-comment

https://github.com/squeek502/AppleSkin/blob/4367b31a05b7da5a75c231b746faad9c2c1fb6d3/java/squeek/appleskin/ModConfig.java#L24-L25

**Comment by Utopia1916** [comment]
well, it seems that only compile a translated version for use. Oh, by the way, I forgot to mention that I using version 2.4.0+mc1.16.5, and I haven't checked the latest version

**Comment by squeek502** [comment]
Fixed by https://github.com/squeek502/AppleSkin/pull/261
