### ISSUE TITLE
When paired with raised, icons are misaligned

### ISSUE THREAD

**Issue by xXLaciWarriorXx** [squeek502/AppleSkin#257]
When paired with the [Raised](https://www.curseforge.com/minecraft/mc-mods/raised) (which fixes the 1px cutoff of the hotbar), the icons are slightly misaligned.

![image](https://github.com/squeek502/AppleSkin/assets/77933659/f07aa664-903d-4bce-a6bc-0e08a6eb5af3)
![image](https://github.com/squeek502/AppleSkin/assets/77933659/1332c757-4e06-4a38-9d3e-c4a217d15f39)

**Comment by squeek502** [comment]
Download the appleskin addon for raised, see https://github.com/squeek502/AppleSkin/issues/252
