### ISSUE TITLE
[1.14] SMP Server Crash on join

### ISSUE THREAD

**Issue by Boomflex** [squeek502/AppleSkin#26]
Hello there,

Fabric: 0.0.0.56
Loader: 0.2.0.70
Appleskin: mc1.14-fabric-1.0.0

https://pastebin.com/ixfVGT8Q

**Comment by squeek502** [comment]
Thanks for reporting, will look into it.

**Comment by squeek502** [comment]
Should be fixed in v1.0.1. You can get it [on Curseforge](https://minecraft.curseforge.com/projects/appleskin/files) once it's approved or [here](https://github.com/squeek502/AppleSkin/releases/tag/v1.0.9).
