### ISSUE TITLE
Visual bug when too much saturation 1.20.1

### ISSUE THREAD

**Issue by zachsai** [squeek502/AppleSkin#262]
![image](https://github.com/squeek502/AppleSkin/assets/63996164/96d47c66-f031-469e-9182-c98dd6f47135)
Is this a bug that it overlaps the food saturation when it gives over 10 hunger bars?

**Comment by squeek502** [comment]
Definitely a bug. Forge or Fabric?

**Comment by zachsai** [comment]
Forge

**Comment by squeek502** [comment]
Fixed by 3906837549bf3db13a3a34d6c6d8c3e22ca5aad5
