### ISSUE TITLE
Please upload appleskin 1.12.2 for forge to modrinth

### ISSUE THREAD

**Issue by ghost** [squeek502/AppleSkin#263]

**Comment by squeek502** [comment]
Unsure if I'll upload the older releases to Modrinth.

Note that if you don't want to use CurseForge, then you can download that version from GitHub instead:

https://github.com/squeek502/AppleSkin/releases/tag/v1.0.14

**Comment by squeek502** [comment]
Ended up putting the most recent versions for Minecraft 1.10, 1.11, 1.12, 1.13, 1.14, and 1.15 on Modrinth.

https://modrinth.com/mod/appleskin/versions?g=1.10.2&g=1.12.2&g=1.14.4&g=1.15.2&g=1.11.2&g=1.13.2
