### ISSUE TITLE
1.19.2 Client startup crash

### ISSUE THREAD

**Issue by Proxwian** [squeek502/AppleSkin#264]
[crash-2023-09-09_20.04.27-fml.txt](https://github.com/squeek502/AppleSkin/files/12565827/crash-2023-09-09_20.04.27-fml.txt)

Looks like mixins issue. Forge 43.2.20

**Comment by Daltaxy** [comment]
same thing on 1.20.1 forge 47.1.46
appleskin-forge-mc1.20.1-2.5.0.jar

[debug.log](https://github.com/squeek502/AppleSkin/files/12565963/debug.log)

edit: switching to the latest forge 47.1.47 does the same thing

**Comment by Proxwian** [comment]
In my case it was causing by ImmediatelyFast mod. Now it fixed in latest version. Hope it helps @Daltaxy
