### ISSUE TITLE
Just a quick question,

### ISSUE THREAD

**Issue by Sterngosling555** [squeek502/AppleSkin#265]
How do I download the mod itself, I don't actually know how to get it onto Minecraft.

**Comment by squeek502** [comment]
First you need to install a mod loader, either Fabric or Forge:

- https://fabricmc.net/use/installer/
- https://files.minecraftforge.net/net/minecraftforge/forge/

Then you download the AppleSkin jar file for the appropriate loader and version of Minecraft you're using (from [CurseForge](https://www.curseforge.com/minecraft/mc-mods/appleskin), [Modrinth](https://modrinth.com/mod/appleskin), or [GitHub](https://github.com/squeek502/AppleSkin/releases)) and put it into the `mods` folder of your Minecraft instance. If you're using Fabric you'll also need to download [the Fabric API](https://curseforge.com/minecraft/mc-mods/fabric-api) jar file and put that into your mods folder, too.
