### ISSUE TITLE
Unable to work in IDE with Fabric and ArchitecturyPlugin

### ISSUE THREAD

**Issue by Bread-NiceCat** [squeek502/AppleSkin#268]
> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'appleskin'!
> java.lang.NoClassFoundError: me/shedaniel/autoconfig/ConfigData

minecraft_version=1.20.1
parchment_version=parchment-1.20.1:2023.08.06@zip
fabric_loader_version=0.14.22
fabric_api_version=0.86.1+1.20.1
isn't install architectury-api

appleskin-fabric-mc1.20.2:2.5.1 //note: i've tried change 1.20.2-2.5.1 to 1.20-2.5.0, but the same exception was thrown
//appleskin-forge-mc1.20:2.5.0 isn't have the problem

Please forgive my poor english =)

More details:

> Here's console log(something not important i've deleted):

> ```
> ---- Minecraft Crash Report ----
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 2023-09-30 08:36:52
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'appleskin'!
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:458)
> 	at net.minecraft.client.main.Main.main(Main.java:211)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
> 	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
> Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at squeek.appleskin.AppleSkin.onInitializeClient(AppleSkin.java:21)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
> 	... 9 more
> Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	... 19 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:458)
>
> -- Initialization --
> Stacktrace:
> 	at net.minecraft.client.main.Main.main(Main.java:211)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
> 	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.20.1
> 	Minecraft Version ID: 1.20.1
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 17.0.4.1, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
> 	Memory: 662724608 bytes (632 MiB) / 1650458624 bytes (1574 MiB) up to 3210739712 bytes (3062 MiB)
> Fabric Mods: 
> 		appleskin: AppleSkin 2.5.1+mc1.20.2
> 		candycraftce: CandyCraft CE 1.0.0
> 		fabric-api: Fabric API 0.86.1+1.20.1
> 		fabric-api-base: Fabric API Base 0.4.30+7abfd51577
> 		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
> 		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
> 		fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
> 		fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
> 		fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
> 		fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
> 		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
> 		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
> 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
> 		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.12+b3afc78b77
> 		fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
> 		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
> 		fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
> 		fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
> 		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
> 		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
> 		fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
> 		fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
> 		fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
> 		fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
> 		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
> 		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
> 		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
> 		fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
> 		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
> 		fabricloader: Fabric Loader 0.14.22
> 		generated_a316709: Generated Mod (Please Ignore) 1.0.0
> 		java: Java HotSpot(TM) 64-Bit Server VM 17
> 		minecraft: Minecraft 1.20.1
> 	Launched Version: Fabric
> 	Backend library: LWJGL version 3.3.1 SNAPSHOT
> 	Backend API: Unknown
> 	Window size: <not initialized>
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: <disabled>
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	CPU: <unknown>
> ```

**Comment by squeek502** [comment]
The 1.20.2 version definitely won't work for 1.20.1.

Are you putting the appleskin jar in your mods folder or are you including it with Gradle using the guide here: https://github.com/squeek502/AppleSkin/tree/1.20.1-fabric#for-mod-developers?

**Comment by Bread-NiceCat** [comment]
fabric-1.20-2.5.1 has the same problem

**Comment by squeek502** [comment]
`appleskin-fabric-mc1.20.1-2.5.1` is the latest 1.20.1 version.

Please provide more information about how you are including AppleSkin in your dev environment.

**Comment by Bread-NiceCat** [comment]
![image](https://github.com/squeek502/AppleSkin/assets/121159360/1338da4e-ad57-478a-b73b-4d76ea88a71c)
Because of the poor network environment, i use the local file instead of the remote

**Comment by squeek502** [comment]
Okay, I was able to reproduce this.

Normally, `cloth-config` is included automatically when using the Maven repository. So, instead, you'll need to provide `cloth-config` manually, too. This worked for me:

![appleskin-268](https://github.com/squeek502/AppleSkin/assets/2389051/e6e448e3-1851-4442-bc34-825701bb8c20)

Note: If you don't need AppleSkin at compile-time, you can just put in in your `run/mods` folder instead of doing anything with Gradle (the `run` directory will be created after importing the project/running Minecraft for the first time).

**Comment by Bread-NiceCat** [comment]
Thank you, I'll try it.

> Note: If you don't need AppleSkin at compile-time, you can just put in in your run/mods folder instead of doing anything with Gradle (the run directory will be created after importing the project/running Minecraft for the first time).

Actually, if I put it in `run/mods` , Mc may crash due to the difference of mapped code and the parchment-ed code. 
Do you have some good ideas?
