### ISSUE TITLE
Add a toggle setting which separates the Saturation and Exhaustion overlays to be separate bars above the hunger bar.

### ISSUE THREAD

**Issue by PlayfulPiano** [squeek502/AppleSkin#270]
Personally I find having all three bars overlayed on top of each other to be a bit cluttered and hard to read (just today I actually learned that the "checkerboard" pattern on my hunger bar wasn't some graphical issue, but an overlay!). This could potentially give some users who want more clarity in the visual. It would have to move the air bar up to compensate, though.

Possible customization could include moving only certain bars up (only saturation or only exhaustion, for example).  Would also mean that it could give users the means to have custom bars for saturation/exhaustion with a resource pack.

**Comment by squeek502** [comment]
Thanks for the suggestion, but I'm happy with how things are currently.
- Exhaustion is not important enough to have its own separate bar that takes up visual space, and the exhaustion underlay can be turned off in the config if it's not wanted
- Saturation being an overlay on the hunger bar accurately reflects how the saturation mechanic works: it is something like a 'buffer' against losing hunger, and it is always limited by the player's hunger value (you can never have more saturation than your current hunger)
- The mod compatibility headaches involved in moving/adding HUD elements is not something I'm interested in dealing with

**Comment by PlayfulPiano** [comment]
I see, that's understandable. By any chance are appleskin's bar texture styles preset in how they're rendered? Because alternatively I wouldn't mind if the exhaustion underlay (which is really my main complaint) could be modified to not use a checkboard structure. I don't know if that would have to be done through a resourcepack or if the mod itself would need a change to allow for a non-checkerboard variation (e.g., a transparent solid bar of some color).

**Comment by squeek502** [comment]
Yep, if you make a resource pack with a custom [`assets/appleskin/textures/icons.png`](https://github.com/squeek502/AppleSkin/blob/1.16-forge/resources/assets/appleskin/textures/icons.png) you can change the checkerboard to whatever you'd like.

**Comment by PlayfulPiano** [comment]
I see, thank you so much.
Does the exhaustion bar have to be opaque or does it support transparency?

**Comment by squeek502** [comment]
PNG support semi-transparent pixels so I'd assume that'd work, but haven't tried it.

**Comment by PlayfulPiano** [comment]
![image](https://github.com/squeek502/AppleSkin/assets/3158887/5cce669e-b72f-4c75-b654-053d0281dafe)

Yep it seems to work well. Again thank you so much for your help.

**Comment by 4unduck** [comment]
Help i'm trying to change the textures to fit with my Vanilla Tweaks resourcepack, what do the 2 lower sprites mean?
