### ISSUE TITLE
[SUGGESTION] Change The Modrinth Page to say that Server is Optional

### ISSUE THREAD

**Issue by LoganTheAroAce** [squeek502/AppleSkin#275]
So I tried to make a Client Side Modpack that adds nothing new, and i wanted to add AppleSkin, But it got rejected. Here is the Rejection Message:
![image](https://github.com/squeek502/AppleSkin/assets/114693438/8bf0a53d-dc19-4b4b-a60a-c7023dd9ddb3)
I Checked and saw that AppleSkin is marked as Required, Despite mostly working when only on the client. I will be Removing AppleSkin for now, But if this gets fixed ill re-add it.

**Comment by squeek502** [comment]
Changed server-side to "Optional"

Let me know if that'll work for you.

**Comment by LoganTheAroAce** [comment]
> Changed server-side to "Optional"
> 
> Let me know if that'll work for you.

Thanks! I Resumitted my Modpack, I just need to wait for it to be either Approved or Rejected. You Saved me a few hours, as I haven't made another version of it without AppleSkin and i can't use my PC Right now.
