### ISSUE TITLE
[1.20.4] [Neoforge] Error during common_setup event phase

### ISSUE THREAD

**Issue by SanteriLoitomaa** [squeek502/AppleSkin#285]
The game gives the following error after failing to load mods:

java.lang.NoClassDefFoundError: net/neoforged/neoforge/network/NetworkRegistry$ChannelBuilder

My guess is that it's caused by the Network rework made in Neoforge version 20.4.70-beta as the game fails to load in that version and the versions after it but starts with no issues in the 20.4.69-beta version.

Here is the full log: https://mclo.gs/uIM5hDE

**Comment by squeek502** [comment]
Fixed by 8b3fad1ddde91b8319a78659b2d7b0df12bcfb76. Will release a new version shortly.
