### ISSUE TITLE
Exhaustion still renders when food hud is cancelled with Forge event

### ISSUE THREAD

**Issue by BrownBear85** [squeek502/AppleSkin#289]
I'm canceling `RenderGuiOverlayEvent` on Forge 1.20.1 when `event.getOverlay() == VanillaGuiOverlay.FOOD_LEVEL.type()` and this successfully cancels the food icons and saturation overlay, however the saturation checkerboard pattern that renders behind the food icons. 

![image](https://github.com/squeek502/AppleSkin/assets/91921122/da316e90-27cb-46ae-bb68-8a2dc4489f8f)

**Comment by squeek502** [comment]
You'll want to cancel both `RenderGuiOverlayEvent.Pre` and `RenderGuiOverlayEvent.Post`.

https://github.com/squeek502/AppleSkin/blob/07dc6b6db4a98626617ceada5e87072653e6ae3f/java/squeek/appleskin/client/HUDOverlayHandler.java#L55-L92
