### ISSUE TITLE
[1.13.2 Forge] Crash on Generating SP World

### ISSUE THREAD

**Issue by Morpheus1101** [squeek502/AppleSkin#29]
Crash Report @ https://pastebin.com/uDYzRXVe

**Comment by squeek502** [comment]
My guess is that either you need to regenerate/fix your AppleSkin config file or AppleSkin needs to be updated for recent Forge versions.

**Comment by Morpheus1101** [comment]
Yeah, i hadnt re-generated configs for quite a few forge versions, so a removal of them an re-gen did indeed work.
