### ISSUE TITLE
No option to disable Bedrockify screen safe area compat when the related mixin is disabled

### ISSUE THREAD

**Issue by archiso86** [squeek502/AppleSkin#294]
I'm using another mod (Overflowing Bars) which does not support Bedrockify moving the hotbar, so I use Raised mod to move it up and disable the screen safe area mixin from Bedrockify (client.features.screenSafeArea). This sets the hotbar back at it's normal position and instead relies on Raised mod to move the hotbar. Now, I set the screen safe area back to 15 so it affects only Bedrockify widgets.
See that the effect to Bedrockify widgets remains without the mixin:
![image](https://github.com/squeek502/AppleSkin/assets/160344941/8e6a4bb1-5fc5-4a68-af18-8047ea4bfac6)
^ (0 screen safe area)

![image](https://github.com/squeek502/AppleSkin/assets/160344941/fa502ffb-0051-4980-b021-6d53b7c87c60)
^ (15 screen safe area)

I prefer to have it at 15 because 0 is right at the screen corner. But AppleSkin mod apparently reads the Bedrockify screen safe area, regardless of the hotbar effects being enabled, and mistakenly places the saturation at where it might be if the hotbar was moved there.
![image](https://github.com/squeek502/AppleSkin/assets/160344941/6d6ef948-4a53-46af-a9f1-429c9ea3f542)
^ (Mixin disabled, screen safe area 15)

Preferred fix might be to add an option to disable the Bedrockify compatibility and/or intelligently disable it when the mixin is not enabled for the hotbar effects.

Raised mod properly affects the Overflowing Bars widgets, this compatibility is not the focus of this issue.
Bedrockify mod does not affect the Overflowing Bars widgets, which is the reason I need this compatibility.

**Comment by squeek502** [comment]
I'm not really sure what you're asking for. There's no Bedrockify compatibility code in AppleSkin.

**Comment by ghost** [comment]
Actually I may be a teensy bit dumb. I should report this to Overflowing Bars because they dont support Bedrockify lifting the widgets up. I'll try there instead, it'll be easier and not require such a dumb solution like using Raised mod instead of Bedrockify.
