### ISSUE TITLE
Food tooltip renders 1px too high on top of item tooltip

### ISSUE THREAD

**Issue by TehNut** [squeek502/AppleSkin#3]
![](http://i.imgur.com/VC3ujH8.png)

This is indev. Not sure if that has anything to do with it.

**Comment by squeek502** [comment]
Good catch, will take a closer look when I can.

**Comment by squeek502** [comment]
Fixed in v1.0.2: https://github.com/squeek502/AppleSkin/releases/tag/v1.0.2
