### ISSUE TITLE
Add appleskin-neoforge-mc1.20.5-3.0.0 crashes

### ISSUE THREAD

**Issue by ModernGamingWorld** [squeek502/AppleSkin#301]
[crash-2024-05-05_20.48.21-client.txt](https://github.com/squeek502/AppleSkin/files/15215249/crash-2024-05-05_20.48.21-client.txt)

![Screenshot 2024-05-05 204952](https://github.com/squeek502/AppleSkin/assets/75923060/6e219c55-b478-4edc-ae91-64c4298c959f)

Neoforge 1.20.6 crashes

**Comment by squeek502** [comment]
Thanks for letting me know. Looks like the relevant breaking change was actually in a 1.20.5 version (20.5.14-beta to be exact):

https://github.com/neoforged/NeoForge/pull/542

**Comment by squeek502** [comment]
Fixed in AppleSkin v3.0.1
