### ISSUE TITLE
Fabric 1.21 port

### ISSUE THREAD

**Issue by cqm3ron** [squeek502/AppleSkin#305]
Would be very nice :D

**Comment by squeek502** [comment]
Done in https://github.com/squeek502/AppleSkin/tree/1.21-fabric

Just need to switch from targeting 1.21-rc1 to 1.21 proper and release it.

**Comment by squeek502** [comment]
Released

https://github.com/squeek502/AppleSkin/releases/tag/v3.0.2
https://www.curseforge.com/minecraft/mc-mods/appleskin (might take a bit to show up)
https://modrinth.com/mod/appleskin

**Comment by Decme** [comment]
The fabric mod for 1.21 is crashing my 1.21 fabric server. No crash logs are generated.

**Comment by squeek502** [comment]
@Decme can't reproduce. What version of Fabric are you using? What version of Fabric API?
