### ISSUE TITLE
AppleSkin crash problem in 1.21

### ISSUE THREAD

**Issue by KozukiYOMA** [squeek502/AppleSkin#307]
It seems to crash when used with kaleido, which is necessary to use Immersive tooltip.

[crash-2024-06-24_18.19.24-client.txt](https://github.com/user-attachments/files/15953138/crash-2024-06-24_18.19.24-client.txt)

Crashes when hovering over food when using AppleSkin and Kaleido at the same time.

Fabric 0.15.11-1.21.0 FabricAPI 0.100.3

**Comment by squeek502** [comment]
I'm not sure there's much I can do on my end, since it looks like Kaleido is trying to cast one of AppleSkin's classes to one of its classes (it's likely missing an `instanceof` check). 

You will need to report this to Kaleido/Immersive:Tooltip.

**Comment by yanggx98** [comment]
It's true that it was missing an instanceof check. I had been fixed it. thx
