### ISSUE TITLE
Crashes when altering max health

### ISSUE THREAD

**Issue by teoWei** [squeek502/AppleSkin#308]
Not sure what is happening exactly.

I made a custom-made datapack that syncs up 2 player's health bar by rapidly altering the max health of the players.
When holding a food that has a preview of potential hearts healed while taking damage, the client crashes.

datapack : [soulbound.zip](https://github.com/user-attachments/files/15964631/soulbound.zip)

**Comment by teoWei** [comment]
Forgot about the crash report:
[crash-2024-06-25_12.20.35-client.txt](https://github.com/user-attachments/files/15964655/crash-2024-06-25_12.20.35-client.txt)

**Comment by squeek502** [comment]
Fixed in v3.0.5, thanks for the report!
