### ISSUE TITLE
Saturation Bar

### ISSUE THREAD

**Issue by W413R** [squeek502/AppleSkin#309]
I have been using this mod for a while and it always worked fine, but when i played the new 1.21 the saturation bar doesnt match with the hunger bar.
![image](https://github.com/squeek502/AppleSkin/assets/123565064/1cc4aacb-75f3-4d39-b53e-dc9f8a3cfb94)

**Comment by squeek502** [comment]
NeoForge or Fabric? Do you have any other mods installed? Do you have a texture pack installed?

**Comment by W413R** [comment]
> Quote reply

Fabric, yes I do. I ''fixed'' it by downloading a resource pack that is compatible with appleskin. Not sure what could cause the normal hunger bar though.

**Comment by squeek502** [comment]
Closing, nothing I can do on my end here.

**Comment by Declan1123** [comment]
> Fabric, yes I do. I ''fixed'' it by downloading a resource pack that is compatible with appleskin. Not sure what could cause the normal hunger bar though.

Hey, im having the same probem, what resource pack did you use?

**Comment by W413R** [comment]
> > Fabric, yes I do. I ''fixed'' it by downloading a resource pack that is compatible with appleskin. Not sure what could cause the normal hunger bar though.
> 
> Hey, im having the same probem, what resource pack did you use?

I searched for resource packs that are compatible with appleskin and there are few of them, I use the beef one.
https://www.planetminecraft.com/texture-packs/tag/appleskin/

**Comment by Declan1123** [comment]
> I searched for resource packs that are compatible with appleskin and there are few of them, I use the beef one. https://www.planetminecraft.com/texture-packs/tag/appleskin/ 
Works, thank you!!!
