### ISSUE TITLE
Latest 1.21 Version is seen as Virus.

### ISSUE THREAD

**Issue by Volak** [squeek502/AppleSkin#310]
Tried downloading from the website below. My computer deleted the downloaded file, flagging it as a virus.

https://modrinth.com/mod/appleskin/version/3.0.2+mc1.21

**Comment by squeek502** [comment]
Same as the times this has happened before:

- https://github.com/squeek502/AppleSkin/issues/236
- https://github.com/squeek502/AppleSkin/issues/234
- https://github.com/squeek502/AppleSkin/issues/107

> This is a false positive. Don't think there's anything I can do on my end to resolve this.
>
> You're always welcome to inspect the source code, build the mod from source yourself, and/or decompile the distributed jar to confirm it matches the source code in the repository.

**Comment by mttic** [comment]
I remember that the Controlify mod had a similar problem with its 1.20 release. I believe you can submit a false positive report to BitDefender to resolve the issue easily, but I'm not sure

**Comment by squeek502** [comment]
@Volak what software flagged it as a virus?

**Comment by squeek502** [comment]
Closing. Nothing I can do about this and no further information was given.
