### ISSUE TITLE
Need an update for NeoForge >= 21.0.82-beta

### ISSUE THREAD

**Issue by hp4701075hp** [squeek502/AppleSkin#313]
Version 1.21 crashes and cannot be used

https://media.discordapp.net/attachments/815819581440262146/1261213840427716629/image.png?ex=6692246b&is=6690d2eb&hm=792749549858a1b38005277b89ff14dd2420412907d82f0b5403f18f747b0d82&=&format=webp&quality=lossless&width=881&height=701

**Comment by squeek502** [comment]
What version of NeoForge?

**Comment by JoshSagnella** [comment]
I get the same error, neoforge version 21.0.86-beta

**Comment by squeek502** [comment]
Thanks, looks like this is probably the relevant change:

- `21.0.82` Update NightConfig and cleanup config code

**Comment by squeek502** [comment]
Fixed in AppleSkin v3.0.4
