### ISSUE TITLE
Tooltips have stopped working in recent JEI versions

### ISSUE THREAD

**Issue by blackaloe** [squeek502/AppleSkin#314]
Please note that we are using a translator, so the meaning may not be conveyed properly. This may be my problem, but it is not compatible with the Croptopia mod. Hunger or satiety are not displayed for food added in Croptopia mode.

**Comment by squeek502** [comment]
What version of Minecraft are you using? Are you using Fabric, Forge, or NeoForge?

**Comment by blackaloe** [comment]
ah. sorry. Due to which mode you are currently using, the hunger value does not appear in the JEI mode recipe screen or the right pane. When viewing the item in the inventory, it displays normally.

**Comment by squeek502** [comment]
Still need information about what Minecraft version and mod loader you are using.

**Comment by squeek502** [comment]
[From CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/appleskin#c1200):

> After updating to the latest July 14th JEI (along with ModernFix), I noticed that AppleSkin isn't working in JEI view anymore. It does work in the inventory as expected. To get it working in JEI again, I had to rollback a couple JEI versions.

**Comment by squeek502** [comment]
Fixed in JEI >= `15.8.0.17` and >= `19.5.0.58`, see https://github.com/mezz/JustEnoughItems/issues/3626#issuecomment-2249255770
