### ISSUE TITLE
Support for custom food icon from resourcepack

### ISSUE THREAD

**Issue by Jacold** [squeek502/AppleSkin#319]
Hi, I'm using vanilla tweaks custom resource pack and I've changed meat icon to apple icon. After installing AppleSkin icons don't match. Any chance for outlining any icon instead of being forced to use default meat icon?
![image](https://github.com/user-attachments/assets/4c3172a8-8e76-405a-955d-c35f4488cdea)

**Comment by squeek502** [comment]
Resource packs can include a custom [`assets/appleskin/textures/icons.png`](https://github.com/squeek502/AppleSkin/blob/1.16-forge/resources/assets/appleskin/textures/icons.png) (or you can make a resource pack with custom AppleSkin textures to match the resource pack you're using)
