### ISSUE TITLE
Crash with Forge 25 b110

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [squeek502/AppleSkin#32]
This does not happen in b108. And many mods are being affected by this, including MineMenu, which also doesn't happen in b108.

https://github.com/dmillerw/MineMenu/issues/51

Crash log: https://hastebin.com/izuzufecec.txt

EDIT: Crashed when joining a server

**Comment by squeek502** [comment]
Thanks for reporting, will look into it.

EDIT: The relevant Forge change: https://github.com/MinecraftForge/MinecraftForge/commit/cdbd84249495e1385e2657fca986229779dd0efc

**Comment by squeek502** [comment]
Fixed in v1.0.11: https://minecraft.curseforge.com/projects/appleskin/files/2698165
