### ISSUE TITLE
request - dynamic gold glint to hunger meter when resource packs change the overall shape of the hunger bar

### ISSUE THREAD

**Issue by bejuazun** [squeek502/AppleSkin#320]
rather than a static gold glint texture around the drumstick it could be dynamic based off the sprite itself, probably not worth the coding effort to get it to be optimized but would be appreciated for those of us who dont use the default drumstick texture.

**Comment by squeek502** [comment]
Resource packs can include a custom [assets/appleskin/textures/icons.png](https://github.com/squeek502/AppleSkin/blob/1.16-forge/resources/assets/appleskin/textures/icons.png) (or you can make a resource pack with custom AppleSkin textures to match the resource pack you're using)
