### ISSUE TITLE
Appleskin attempts to send packets to fake players

### ISSUE THREAD

**Issue by IThundxr** [squeek502/AppleSkin#322]
Relevent section of the log: https://mclo.gs/rNHZ5UC

Attempting to make a npc from https://modrinth.com/mod/taterzens sit on a create seat crashes the server since appleskin tries sending the npc (which is a fake player) packets, simply checking for !(player instanceof FakePlayer) should be enough to fix this

Minecraft 1.20.1
Modlist: https://github.com/Layers-of-Railways/modpack/blob/1.20.1/dev/modlist.md

**Comment by squeek502** [comment]
Any reason this was closed?
