### ISSUE TITLE
Question :Can you make mod in Liteloader1.12.2?

### ISSUE THREAD

**Issue by RoyanAB** [squeek502/AppleSkin#325]
Hello,i need appleskin in liteloader 1.12.2
![image](https://github.com/user-attachments/assets/1b5a3493-2468-4045-bbe3-5c110f3b4ae6)

**Comment by squeek502** [comment]
I have no plans to do this. You/anyone else is free to create a Liteloader version of the mod if they would like, though (see [the license](https://github.com/squeek502/AppleSkin/blob/1.16-forge/LICENSE)).
