### ISSUE TITLE
Appleskin common setup crash custom modpack

### ISSUE THREAD

**Issue by Epicender12** [squeek502/AppleSkin#328]
[latest.log](https://github.com/user-attachments/files/16999697/latest.log)
[crash-2024-09-13_17.54.59-fml.txt](https://github.com/user-attachments/files/16999699/crash-2024-09-13_17.54.59-fml.txt)

**Comment by squeek502** [comment]
You're using AppleSkin for 1.18.2 but Minecraft 1.19.2
