### ISSUE TITLE
mod texture editability

### ISSUE THREAD

**Issue by normie-chan** [squeek502/AppleSkin#329]
How would one edit the textures for this pack, I have a custom food bar that doesn't match with the mod's saturation bar and I'd like to make my own texture for the thing so it works right. That is all.

**Comment by normie-chan** [comment]
![Uploading 2024-09-21_19.04.37.png…]()

**Comment by squeek502** [comment]
Include a custom [assets/appleskin/textures/icons.png](https://github.com/squeek502/AppleSkin/blob/1.16-forge/resources/assets/appleskin/textures/icons.png)

**Comment by squeek502** [comment]
Your image didn't get uploaded properly, but I'm assuming it would look similar to the one in https://github.com/squeek502/AppleSkin/issues/319.

Closing for now, let me know if you have any issues getting it to work.
