### ISSUE TITLE
Suggestion: control over hunger.

### ISSUE THREAD

**Issue by Milliath** [squeek502/AppleSkin#33]
I understand this mod is to make GUI more informative, but as an old mc player who is nostalgic for  no-hunger gameplay, I'd be happy to see an option to turn off the hunger on Easy+, or something more advanced like configurable saturation time, disable hunger loss while sprinting/regenerating and so on.
Thanks.

**Comment by squeek502** [comment]
That is out of scope for this mod. There are other mods that do some of what you want:

- Disable hunger: https://minecraft.curseforge.com/projects/hunger-strike
- If you know how to code, then you'd be able to write a mod that configures hunger in whatever way you want using AppleCore: https://github.com/squeek502/AppleCore/wiki/Using-the-AppleCore-API
