### ISSUE TITLE
Support for 1.21.4?

### ISSUE THREAD

**Issue by LCSOGthb** [squeek502/AppleSkin#338]
When the mod support minecraft latest version 1.21.4?

**Comment by cassiancc** [comment]
The mod works with 1.21.4 out of the box, but should be be marked as compatible with 1.21.4 on Modrinth.

**Comment by squeek502** [comment]
Confirmed that the 1.21.3 versions work for 1.21.4. Marked as such on Modrinth and CurseForge

**Comment by LCSOGthb** [comment]
Thanks

**Comment by codedev9** [comment]
when i used apple skin on 1.21.4 i got a crash mesaage, i use 1.21.4 btw

**Comment by squeek502** [comment]
@codedev9 please open a new issue and post your crash log
