### ISSUE TITLE
There was a problem during loading 

### ISSUE THREAD

**Issue by mcmso** [squeek502/AppleSkin#39]
[crash-2019-05-23_20.08.23-client.txt](https://github.com/squeek502/AppleSkin/files/3212066/crash-2019-05-23_20.08.23-client.txt)

**Comment by squeek502** [comment]
Wrong mod. This looks like a [Spice of Life: Carrot Edition](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues) crash:

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Spice of Life: Carrot Edition (solcarrot)
Caused by: java.lang.NullPointerException
```

**Comment by mcmso** [comment]
> Wrong mod. This looks like a [Spice of Life: Carrot Edition](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues) crash:
> 
> ```
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Spice of Life: Carrot Edition (solcarrot)
> Caused by: java.lang.NullPointerException
> ```
Thank you for your reply. The other two authors have contacted
