### ISSUE TITLE
Option to adjust location of saturation overlay in config?

### ISSUE THREAD

**Issue by sweetsosweet** [squeek502/AppleSkin#4]
I ask because I'm using the mod [Additional Status ](https://minecraft.curseforge.com/projects/additionalstatus) and the overlay is now too high. [Picture with Default](http://i.imgur.com/9DIcwit.png). [Picture with Resource pack](http://i.imgur.com/AjMrWaK.png) 

I realize it's not the fault of this mod, I'm just looking for a workaround.

**Comment by squeek502** [comment]
Fixed in v1.0.3: https://github.com/squeek502/AppleSkin/releases/tag/v1.0.3

**Comment by sweetsosweet** [comment]
Wow! Thanks a ton, that was an amazingly fast turnaround. :D
