### ISSUE TITLE
[1.14.2] Screen refactors cause a crash in dev

### ISSUE THREAD

**Issue by LemmaEOF** [squeek502/AppleSkin#40]
All the names for screens got refactored *again* with 1.14.2, so trying to enter survival mode with AppleSkin installed causes the game to crash due to a `java.lang.ClassNotFoundException: net.minecraft.client.gui.Screen`. It's now at `net.minecraft.client.gui.screen.Screen` instead. Because of intermediary mapping, this *only* happens in dev environments.

**Comment by squeek502** [comment]
Thanks for the heads up.

**Comment by squeek502** [comment]
Assuming this is no longer relevant at this point.
