### ISSUE TITLE
Client crash on startup 

### ISSUE THREAD

**Issue by Minigamer42** [squeek502/AppleSkin#41]
> ---- Minecraft Crash Report ----
> // This doesn't make any sense!
> 
> Time: 6/11/19, 12:45 AM
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
> 	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
> 	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
> 	at net.minecraft.class_310.method_1503(class_310.java)
> 	at net.minecraft.class_310.method_1514(class_310.java:395)
> 	at net.minecraft.client.main.Main.main(Main.java:154)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/network/ClientSidePacketRegistry
> 		at squeek.appleskin.network.SyncHandler.init(SyncHandler.java:26)
> 		at squeek.appleskin.AppleSkin.onInitializeClient(AppleSkin.java:11)
> 		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
> 		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
> 		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
> 		... 11 more
> 	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.network.ClientSidePacketRegistry
> 		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
> 		at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
> 		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 		... 16 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
> 	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
> 	at net.minecraft.class_310.method_1503(class_310.java)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.class_310.method_1514(class_310.java:395)
> 	at net.minecraft.client.main.Main.main(Main.java:154)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.14.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 11.0.1, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 865494208 bytes (825 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
> 	JVM Flags: 10 total; -XX:-OmitStackTraceInFastThrow -Xms1024M -Xmx4096M -XX:MetaspaceSize=128M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Launched Version: 1.14.2
> 	LWJGL: 3.2.1 build 12
> 	OpenGL: NO CONTEXT
> 	GL Caps: 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Resource Packs: ~~ERROR~~ NullPointerException: null
> 	Current Language: ~~ERROR~~ NullPointerException: null
> 	CPU: <unknown>

Currently using fabricloader@0.4.8+build.155 and appleskin@1.0.6 which should to my knowlegde work fine together.

**Comment by Minigamer42** [comment]
Also installed this using ATLauncher

**Comment by squeek502** [comment]
Do you have [Fabric API](https://minecraft.curseforge.com/projects/fabric) installed?

**Comment by Minigamer42** [comment]
Tried with and without it, same result.

**Comment by squeek502** [comment]
AppleSkin requires Fabric API, and the error in the log is:
```
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.network.ClientSidePacketRegistry
```
which is a Fabric API class. Do you get a different error when you have Fabric API installed or the same error?

**Comment by Minigamer42** [comment]
I'll send both crash reports tomorrow ^^

**Comment by squeek502** [comment]
I can only reproduce your crash when I don't have Fabric API installed. Double/triple check that you have it installed.

Looks like Fabric's mod.json format [uses `depends` instead of `requires` now](https://github.com/FabricMC/fabric-example-mod/commit/78fb3e428814715d621551ef66e3f81627767491) which is why the error is confusing. Will fix that for the next version.

**Comment by Minigamer42** [comment]
I found the error. ATLauncher puts the fabric API in a folder called "jarmods" which might not be detected by the fabric launcher. I manually moved it from there to "mods" and it's working...
