### ISSUE TITLE
[Suggestion]TAN Support?

### ISSUE THREAD

**Issue by IdrisQe** [squeek502/AppleSkin#45]
There used to be a mod called AppleJuiceSkin which was made to complement this mod running alongside Tough As Nails. It did everything this did, but for TAN's Thirst/Drink system. Unfortunately, AppleJuiceSkin completely vanished from Curseforge for no apprarent reason and its author hasn't responded to my questioning as to why. So, with that seemingly dead in the water, I suppose the best place to ask about support would be here.

Granted, 1.12.2 is probably not getting many more updates now that people are starting to shift to 1.14 but I figured it would be worth asking anyway. Not a huge deal either way since I happen to still have an old file of AJS to use in a current pack with TAN but ah...

**Comment by squeek502** [comment]
I'd prefer this feature be added by Tough As Nails, as there's nothing about AppleSkin that would make this easier to implement on my end (i.e. the code that would be added to AppleSkin for this feature could be put in TAN itself without any changes at all), and the separation between TAN/AppleSkin would make it harder for me to maintain.
