### ISSUE TITLE
Creating a new mod for Tough As Nails

### ISSUE THREAD

**Issue by StellaBiscuit** [squeek502/AppleSkin#46]
You see it! We will need to create a mod for Tough As Nails and Apple Skin compatibility!
I tried to see if the dev's of TAN want to make the same thing that Apple Skin do, for the thirst and hydratation system, but they don't want because it means creating a new mod. 
I will need your help (and I will try to have the help of TAN dev's too) to make a new mod!
I have an idea to get the help of TAN dev's, I will say that I'm creating the mod and I would need some help for, exemple, how the thirst work, by doing this, TAN dev's will help us, without knowing that you are helping too. Genius!
The only problem is that I didn't made any mods (exept with mcreator) but I'm a quick learner so that's not really a problem

**Comment by StellaBiscuit** [comment]
I created the mod project (in case that you accept) here is the [link](https://www.curseforge.com/minecraft/mc-mods/water-drop) (don't know if you can access it even if I made you as an author)

**Comment by squeek502** [comment]
Sorry, not interested. You're welcome to create a mod like this on your own (and adapt any code from AppleSkin you'd like, see [its license](https://github.com/squeek502/AppleSkin/blob/1.12/LICENSE)), but I'm not interested in maintaining yet another mod.
