### ISSUE TITLE
Underlay not showing up

### ISSUE THREAD

**Issue by EnzoIsPrettyCool** [squeek502/AppleSkin#51]
the exhaustion underlay isn't showing up when enabled in the config, 1.12.2 and forge 14.23.5.2838

**Comment by EnzoIsPrettyCool** [comment]
also the flashing preview is just wrong, its showing one shank flashing but when i eat the item it fills 2 and 1/2. Im using it in conjunction with hunger overhaul if that matters aswell

**Comment by squeek502** [comment]
These both sound like server synchronization issues:

- Underlay not showing up probably means you don't have AppleSkin installed on your server. Exhaustion is not synced from the server to the client by vanilla, so AppleSkin must be on the server to get that information
- Hunger being different likely means that your Hunger Overhaul settings are different between your client and your server. You would need to copy your HO config files from your server to your client to fix that.

Closing this for now; reopen if you are still having issues.

**Comment by squeek502** [comment]
These both sound like server synchronization issues:

- Underlay not showing up probably means you don't have AppleSkin installed on your server. Exhaustion is not synced from the server to the client by vanilla, so AppleSkin must be on the server to get that information
- Hunger being different likely means that your Hunger Overhaul settings are different between your client and your server. You would need to copy your HO config files from your server to your client to fix that.

Closing this for now; reopen if you are still having issues.

**Comment by squeek502** [comment]
These both sound like server synchronization issues:

- Underlay not showing up probably means you don't have AppleSkin installed on your server. Exhaustion is not synced from the server to the client by vanilla, so AppleSkin must be on the server to get that information
- Hunger being different likely means that your Hunger Overhaul settings are different between your client and your server. You would need to copy your HO config files from your server to your client to fix that.

Closing this for now; reopen if you are still having issues.
