### ISSUE TITLE
[1.14.4] Does not show saturation upon selection in hotbar.

### ISSUE THREAD

**Issue by fuzzyweapon** [squeek502/AppleSkin#53]
1.  Load/connect to SP/MP world.
2.  Equip any food in the hotbar (vanilla or mod food).
3.  Observe food saturation effects.

There are no food saturation effects.

## Versions
Minecraft 1.14.4
Forge 28.1.26
AppleSkin 1.0.12

**Comment by squeek502** [comment]
Any other mods installed? Tried AppleSkin on its own to see if it still happens?

**Comment by fuzzyweapon** [comment]
Yeah.  I think I might know what's going on.  I just put Flexible Skills into our modpack, which gates saturation display (this feature).  However, I don't think they are handling it correctly and pulling off all of the fx, bc I can still see what looks like to be a part of AppleSkin saturation effect left (just not the shiny gold part which I assume is tied to the animation).

I'm closing this bug and I'll open one with them.  Sorry for the false report!
