### ISSUE TITLE
Insta crash

### ISSUE THREAD

**Issue by varappdev** [squeek502/AppleSkin#58]
My minecraft crashes if I try to load a world with this mod
[crash-2019-12-14_16.07.24-client.txt](https://github.com/squeek502/AppleSkin/files/3964018/crash-2019-12-14_16.07.24-client.txt)

**Comment by squeek502** [comment]
Not sure if this is related to AppleSkin, looks more like an optifabric crash. The crash doesn't happen when you remove AppleSkin?

**Comment by varappdev** [comment]
Nevermind I realised that optifabric broke and its not doing what is supossed to do. This happends without any other mods. I just do not know how to read the crash report
