### ISSUE TITLE
[1.12.2] Modified vanilla fish items not displaying correctly

### ISSUE THREAD

**Issue by luke-bravenboer** [squeek502/AppleSkin#60]
AppleSkin isn't reflecting the changes to the foodValue / saturationModifier for any of the `<minecraft:fish:*>` or `<minecraft:cooked_fish:*>`.

(Note: strictly for Minecraft 1.12, before the vanilla fish items were split into separate IDs)

I've been testing Mrbysco's latest update to FoodTweaker, which added support for modifying food items with metadata (such as fish / golden apple variants).
I'm using a simple test script for FoodTweaker which modifies a list of vanilla foods to give maximum food and saturation values so that I can quickly confirm that changes have been applied correctly.
(see the script here for more info: https://paste.dimdev.org/raruxadogi.xml)

As demonstrated in this screenshot, it's working as intended for most foods, including those with metadata such as the 'enchanted' golden apple:
![2020-03-11_11 03 57](https://user-images.githubusercontent.com/3400211/76363593-3ab71300-6388-11ea-84ab-e7e4a58216c8.png)

However, it's not displaying the updated information for the any of the 4x minecraft:fish or the 2x minecraft:cooked_fish:
![2020-03-11_10 53 04](https://user-images.githubusercontent.com/3400211/76363812-adc08980-6388-11ea-813a-0c3c30519775.png)
...Even though eating one does indeed restore my hunger bar to full, as demonstrated in the comparison with the next screenshot:
![2020-03-11_10 58 13](https://user-images.githubusercontent.com/3400211/76363909-ea8c8080-6388-11ea-8c5a-8edee64caad9.png)

~

Versions:
* Minecraft 1.12.2
* Forge 14.23.5.2847
* AppleSkin-mc1.12-1.0.9
* CraftTweaker2-1.12-4.1.20
* FoodTweaker-1.1.1

Original issue on FoodTweaker's side: https://github.com/Mrbysco/FoodTweaker/issues/2

**Comment by luke-bravenboer** [comment]
For the FoodTweaker developer's explanation of why this problem exists, see this comment:
https://github.com/Mrbysco/FoodTweaker/issues/2#issuecomment-597341008

**Comment by squeek502** [comment]
This type of incompatibility is what [AppleCore](https://github.com/squeek502/AppleCore) was made to prevent. FoodTweaker would need to stop overwriting FoodStats (which would cause problems with any other mod that overwrites FoodStats [hence the need for something like AppleCore]) and use [AppleCore's API to modify the values of the foods](https://github.com/squeek502/AppleCore/blob/HEAD/java/squeek/applecore/api/food/FoodEvent.java) instead (or, alternatively, only use the AppleCore stuff if it's present if they don't want to add a hard dependency).

**Comment by squeek502** [comment]
There's also [Hunger Tweaker](https://www.curseforge.com/minecraft/mc-mods/hungertweaker) which is an AppleCore-compatible version of the same type of mod as FoodTweaker.

**Comment by Mrbysco** [comment]
I would say close the issue and use Hunger Tweaker if you're going to use AppleSkin just to be safe. I'll make a note for myself to look into making FoodTweaker AppleCore compatible in the future. 

I didn't even know Hunger Tweaker existed when I started FoodTweaker. <3
