### ISSUE TITLE
Exhaustion unavailable in multiplayer

### ISSUE THREAD

**Issue by Boobies** [squeek502/AppleSkin#64]
Hi. I'm using the 1.0.9 for 1.16 and I've noticed that while available in single player, the exhaustion bar does not appear in multiplayer. I don't think this is information that is unavailable to the client.

**Comment by squeek502** [comment]
The mod has to be installed on the server for exhaustion to work. Is the mod on your server?

**Comment by Boobies** [comment]
No. I am surprised to learn that, as I figured this was client-side information. Sorry for wasting your time.
