### ISSUE TITLE
[1.10.2] - Compatibility Suggestion.

### ISSUE THREAD

**Issue by XvSkItZvX** [squeek502/AppleSkin#7]
I've been testing this with a mod pack, which can be found [here](http://www.modlister.com/user/XvSkItZvX), noticed that thirst mechanic, from the "Tough as Nails" mod behaves as though there is some sort of saturation(hydration) mechanic. There is no overlay noting this like the saturation you provide for food.

I thought it would be a nice convenience if that could be added to the Apple Skin mod.

**Comment by squeek502** [comment]
Are you sure this isn't a bug? Tough as Nails should add a thirst meter to the HUD. This is linked from their Curse description: http://i.imgur.com/62lCMcw.gif

**Comment by XvSkItZvX** [comment]
They have water droplets much like vanilla chicken legs, However the behavior of the gauge leads me to believe there is another mechanic that behaves like vanilla saturation. And thought if you could bring it to the UI that would be a nice addition.

**Comment by squeek502** [comment]
If that's the case, then it'd make much more sense for them to implement it themselves. Feel free to suggest it to the Tough as Nails devs.

**Comment by XvSkItZvX** [comment]
Fair enough lol.
