### ISSUE TITLE
Exhaustion bar is copied with very high exhaustion levels (200+)

### ISSUE THREAD

**Issue by James103** [squeek502/AppleSkin#71]
As of AppleCore 3.4.0 for MC 1.12.2 plus AppleSkin 1.0.9, with a high enough exhaustion cap, it is possible to get the exhaustion bar to copy itself multiple times, like so:
![image](https://user-images.githubusercontent.com/37945304/83929659-cc50d980-a759-11ea-80bb-5472f742d035.png)

To reproduce:
1. Install the aforementioned mods. For easier reproduction, also install Scaling Feast 1.5.0 by @yeelp, which sets the exhaustion cap to `Float.MAX_VALUE`.
2. In the configs for Scaling Feast, set `food cap` -> `Hunger Damage Multiplier` to a value higher than 0.
3. If you have set `Hunger Damage Multiplier` to 1.0, then do `/gamerule mobGriefing false` (recommended) and then `/summon creeper ~ ~ ~ {Fuse:0,ExplosionRadius:127}`. This will cause you to take ~2,600 HP of damage, gaining over 10,000 exhaustion points in the process.
4. If you have set `Hunger Damage Multiplier` to 1000.0, then find or summon a hostile mob and let it attack you. This will also cause you to gain thousands of exhaustion points.
5. Take a look at the exhaustion bar.

**Comment by yeelp** [comment]
I actually opened an issue here not too long ago about this (see #66) which seems to have been patched, but I don't think the patch has been released yet.

**Comment by James103** [comment]
Duplicate of #66

**Comment by squeek502** [comment]
Finally got new versions released, sorry for the delay.
