### ISSUE TITLE
[Suggestion] A version for 1.8.9

### ISSUE THREAD

**Issue by gBasil** [squeek502/AppleSkin#72]
Does one exist?

**Comment by GirafiStudios** [comment]
Prior to 1.10.2 the features in Apple Skin was a part of Apple Core. The latest version of Apple Core for 1.8.9 can be found here: https://www.curseforge.com/minecraft/mc-mods/applecore/files/2530880

**Comment by GunnerBasil** [comment]
is that client side only?

**Comment by squeek502** [comment]
It can be installed client-side only, but saturation and exhaustion won't be totally correct unless it's on the server as well.

**Comment by GunnerBasil** [comment]
ah ok. thanks!
