### ISSUE TITLE
Move the Fabric Version to it's own Curseforge Project

### ISSUE THREAD

**Issue by nmarshall23** [squeek502/AppleSkin#74]
The Twitch launcher will happily install the Fabric version when it's the latest version.

As a Modpack builder I have no easy way of knowing that this project support both Forge and Fabric.

**Comment by GirafiStudios** [comment]
Personally I think this is a bad idea. The problem lies within how poorly CurseForge handels things.
As Overwolf have recently acquired CurseForge, hopefully they'll start to fix some of the issues the site has.

**Comment by nmarshall23** [comment]
Fair enough, sounds like a Will Not Fix / CurseForge's Issue.

That's fine. Just letting you know anyone who uses CurseForge API to keep their modpack up to date is screwed when mod's keep both Fabric and Forge Version in the same CurseForge Project. I can no longer trust that running an update will give me the latest version of that mod.

**Comment by squeek502** [comment]
@nmarshall23 I've been making sure to mark all Fabric versions as 'beta' rather than 'release.' Does that not affect anything? I was hoping it would.
