### ISSUE TITLE
[1.12.2] 1.0.14 requieres JEI 4.6

### ISSUE THREAD

**Issue by GamerXD8991** [squeek502/AppleSkin#78]
as stated in the title the version 1.0.14 (listed as 1.12.2 mod in Curseforge) shows error on bootup that JEI version 4.6 is required. But 1.12.2 only has JEI version 4.16.XXX

**Comment by squeek502** [comment]
4.16 is > 4.6, so that should work. What version of JEI do you have installed?

**Comment by squeek502** [comment]
Looks like a JEI bug: https://github.com/mezz/JustEnoughItems/issues/2067
