### ISSUE TITLE
Crash when loading Appleskin

### ISSUE THREAD

**Issue by SouthernPixel** [squeek502/AppleSkin#80]
It basically just crashes the game when I load the game. It'll load some mods but as soon as it gets to "Appleskin" it crashes.
Here is the crash report from pastebin
https://pastebin.com/s2YMgNBf

It worked fine before so I have no idea why it isnt working anymore, I updated the mod already.

**Comment by squeek502** [comment]
It looks like you're trying to load the Fabric version of AppleSkin. Double check that you don't have multiple AppleSkin files in in your mods folder. Could also try reinstalling AppleSkin and make sure you're using the right version.

**Comment by SouthernPixel** [comment]
oh wow ok, I could have sworn I downloaded the right version. I already had the right version for 1.12.2 but i guess that got lost somewhere else somehow. Thanks
