### ISSUE TITLE
About Advertise and Share

### ISSUE THREAD

**Issue by 800805** [squeek502/AppleSkin#82]
Hello,I'm a Chinese Minecraft player.Can I advertise this wonderful mod to MCBBS(https://www.mcbbs.net) ?I'll let more people know it.MCBBS is the largest Minecraft forum in China,Many player are seeking good mods there.You know not all of them are good at English, they can't read your post (Even with Google translator) they need a Chinese translator.I'll mark you as the author and I'll send you a link after I finish the post.I'll show them your Curseforge page and let them download the mod there.I'll NEVER claim it as mine, I just wanna translate it and let more people know it.Hope for your reply!Thank you!

**Comment by squeek502** [comment]
Sure, go ahead. It looks like there might already be a thread for AppleSkin, though: https://www.mcbbs.net/forum.php?mod=viewthread&tid=808144
