### ISSUE TITLE
About Share Again

### ISSUE THREAD

**Issue by 800805** [squeek502/AppleSkin#83]
Tow hours ago,you said "Sure, go ahead. It looks like there might already be a thread for AppleSkin, though: https://www.mcbbs.net/forum.php?mod=viewthread&tid=808144"
Yes, you are right.But the administrator deleted it long ago because the man was violations who shared it.
So,can I advertise this wonderful mod to MCBBS again?I'll let more people know it.I'll send you a link after I finish the post.I'll show them your Coursfoger page and let them download the mod there.Hope for your reply and looking forward that you can make more and more good mods.Thank you!

**Comment by squeek502** [comment]
Yes, go ahead.

**Comment by 800805** [comment]
> Yes, go ahead.

Thank you！
https://www.mcbbs.net/thread-1141428-1-1.html
