### ISSUE TITLE
[1.16.4 Forge] Food and saturation numbers render behind items

### ISSUE THREAD

**Issue by ocram9** [squeek502/AppleSkin#84]
When hovering over a food item that has more then 10 saturation or hunger points, it renders the numbers behind items in JEI and the players inventory (see screenshot). I tested this with appleskin, JEI and Simple Farming installed (the last mod adds food items with more saturation and hunger then vanilla).

**Screenshot**
![Screenshot_14](https://user-images.githubusercontent.com/49008532/103251232-304a2200-4978-11eb-9902-141c973e252a.png)

**Versions**
- Forge 35.1.28
- Minecraft 1.16.4
- AppleSkin-mc1.16.2-forge-1.0.14

**Comment by squeek502** [comment]
Should be fixed in 2.0.0
