### ISSUE TITLE
Configuration GUI is broken

### ISSUE THREAD

**Issue by James-E-A** [squeek502/AppleSkin#85]
The `Configuration` button is greyed-out and non-functional:

![Screenshot from 2020-12-28 18-23-51](https://user-images.githubusercontent.com/2776014/103252385-e04c6a80-4939-11eb-852c-681b19e8a84d.png)

This is on
* Minecraft 1.16.4
* Forge 35.1.4
* AppleSkin 1.0.14

*(Yes, I know the screenshot already has those, but I'm including them for indexing if this issue is searched later)*

**Comment by GirafiStudios** [comment]
Forge removed the config GUI in 1.13, so it's currently not possible for mods to do anything with that button.

**Comment by James-E-A** [comment]
Ah, you're right

This issue depends on https://github.com/MinecraftForge/MinecraftForge/pull/7395

**Comment by James-E-A** [comment]
1. For Forge, could this be re-opened with the `forge` and `upstream` labels?

2. For Fabric, it looks like the [ModMenu API](https://github.com/TerraformersMC/ModMenu/wiki/API) is actively maintained and provides a classic UX

(I took the below screenshots)

![Screenshot from 2021-01-18 17-14-21](https://user-images.githubusercontent.com/2776014/104972994-a1498c00-59b0-11eb-95ab-249a38f8c03b.png)

![Screenshot from 2021-01-18 17-13-35](https://user-images.githubusercontent.com/2776014/104972962-8b3bcb80-59b0-11eb-8e67-ec661d4080f6.png)

![Screenshot from 2021-01-18 17-14-58](https://user-images.githubusercontent.com/2776014/104973015-b7574c80-59b0-11eb-8d3e-6a07ca8ca149.png)

**Comment by squeek502** [comment]
Looks like the Forge PR got rejected: https://github.com/MinecraftForge/MinecraftForge/pull/7395#issuecomment-779515483

I don't keep up with the Forge ecosystem so if a 'standard' library for this gains consensus in the future please add a link to it here.

**Comment by GirafiStudios** [comment]
PR for config GUI in Forge is in the works https://github.com/MinecraftForge/MinecraftForge/pull/8874

**Comment by squeek502** [comment]
I'm going to close this and suggest using [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) for the NeoForge/Forge versions of AppleSkin. From my (limited) testing, AppleSkin integrates just fine with it.

Related follow-up for Fabric: https://github.com/squeek502/AppleSkin/issues/303
