### ISSUE TITLE
Feature Request: off-hand food hunger preview changes

### ISSUE THREAD

**Issue by James-E-A** [squeek502/AppleSkin#86]
I always run around with a baked potato in my off-hand.

The UI showing these *empty* hunger elements as *visually* not-exactly-empty over 50% of the time (including fading in/out) is very distracting and confusing to have engaged permanently. (However, the preview is certainly too useful to pass up entirely.)

I was wondering if any of the following could be implemented as an option **for food in the off-hand**:

* Disabling it entirely: only food in the main hand has its hunger previewed
* Reduce it: e.g. blinking only every *other* time
* Discretize it: remove the fade-in and fade-out animation

Thanks,  
-- James

**Comment by squeek502** [comment]
Config option added in v2.0.0
