### ISSUE TITLE
Fabric edition is not configurable

### ISSUE THREAD

**Issue by James-E-A** [squeek502/AppleSkin#88]
When I switched from Forge to Fabric, I noticed that AppleSkin seemed to be ignoring its config file now. (In particular, `showFoodValuesHudOverlay` is ignored.)

I tried copying the file `config/appleskin-client.toml` to `config/fabric/appleskin-client.toml`, but that did not fix it.

Is there something else that needs to be done to configure the Fabric edition (in which case I'll happily send a PR to update the documentation), or is this a bug in the code?

**Comment by squeek502** [comment]
The Fabric version isn't configurable yet. Been something I've been meaning to do for a while, but haven't gotten around to it. Related: https://github.com/squeek502/AppleSkin/issues/85

**Comment by Lv44EnderShaman** [comment]
I'm glad this is something in progress, because it was a concern of mine for a while starting to use it on Fabric compared to Forge. If there's anything a contributor can do to help, let it be known; it's always handy to lift a burden off of someone when they need it.

**Comment by SAGESSE-CN** [comment]
@squeek502 In `Fabric` use the `JSON` to configure the implementation, is right?

**Comment by squeek502** [comment]
I think for Fabric the standard is to use Cloth + AutoConfig:
- https://shedaniel.gitbook.io/cloth-config/
- https://shedaniel.gitbook.io/cloth-config/setup-cloth-config/cloth-config-fabric
- https://shedaniel.gitbook.io/cloth-config/auto-config/introduction-to-auto-config-1u

**Comment by squeek502** [comment]
Config added in v2.0.0
