### ISSUE TITLE
[1.11.2] Food tooltip is misleading when another mod modifies the maximum hunger value

### ISSUE THREAD

**Issue by jesmores** [squeek502/AppleSkin#9]
When Better With Mods is installed and HCHunger is enabled, the tooltips added by Appleskin to food items are misleading. It represents hunger restored as "drumstick" icons, but it seems the no. of drumsticks to value mapping is not based on a percentage because when the max hunger is changed the tooltip stays the same.

More info here: https://github.com/BeetoGuy/BetterWithMods/issues/346#issuecomment-301347873

Appleskin 1.0.6

**Comment by primetoxinz** [comment]
In HCHunger we scale the hunger value by 6 to allow for more precise hunger values. 
If you are willing to add support for this feature I have added an [event](https://github.com/BeetoGuy/BetterWithMods/blob/21a87969b0fdce09cec0c834a45eccb60d88d861/src/main/java/betterwithmods/api/FeatureEnabledEvent.java) to our API to detect when HCHunger is enabled, or any Feature for that matter. Just subscribe and if "hchunger" is enabled, then divide the food value by 6, and it *should* be accurate.

**Comment by GirafiStudios** [comment]
@primetoxinz I'm pretty sure the easiest way to resolve this, would be for you to use the Apple Core API. Pretty sure there is something in there for exactly this. Can't really remember though, been a long time since I looked at it.
Whenever @squeek502 is around, I'm sure he can give a very good explanation at how to use it.

**Comment by primetoxinz** [comment]
Currently HCHunger is completely incompatible with AppleCore due to having to replace FoodStats with our own implementation. We have discussed with him on how to fix the incompatibility but really didn't get anywhere. Would love to fix it in that way, but don't think it's viable currently.

**Comment by GirafiStudios** [comment]
Alright sorry, wasen't aware of the incompatibility.

**Comment by primetoxinz** [comment]
Not a problem, just letting you know

**Comment by squeek502** [comment]
@primetoxinz how should saturation be handled? Seems like you have a completely different system for that? Should I just disable showing saturation in tooltips if `hchunger` is enabled?

**Comment by primetoxinz** [comment]
I'm not a 100% on saturation as I didn't write it, but I believe it is also just a 6x scale and changed to white to represent fat rather than yellow
