### ISSUE TITLE
Need a way for Fabric mods to be able to cancel AppleSkin HUD rendering

### ISSUE THREAD

**Issue by CammiePone** [squeek502/AppleSkin#94]
As a vampire, the saturation overlay provided by AppleSkin obscures the blood bar, making it difficult for vampires to know if they're full on blood.

![image](https://user-images.githubusercontent.com/16853086/110259845-bafe5d00-7f77-11eb-9ff5-4b129a703e5b.png)

**Comment by williambl** [comment]
It does the same thing with Haema - it'd be useful to have an API that exposed `ShowSaturationOverlay`/`ShowExhaustionOverlay`/etc. events, that mods can use to cancel overlays.

**Comment by squeek502** [comment]
For Forge, if mods cancel `RenderGameOverlayEvent.Pre`/`RenderGameOverlayEvent.Post` when `event.getType() == RenderGameOverlayEvent.ElementType.FOOD` then AppleSkin won't render its HUD.

https://github.com/squeek502/AppleSkin/blob/e32016dde3565d88397adddafd61ec7e8869942b/java/squeek/appleskin/client/HUDOverlayHandler.java#L39-L48

https://github.com/squeek502/AppleSkin/blob/e32016dde3565d88397adddafd61ec7e8869942b/java/squeek/appleskin/client/HUDOverlayHandler.java#L62-L69

**Comment by MoriyaShiine** [comment]
Both Haema and Bewitchment are fabric mods, we don't have that option.

**Comment by squeek502** [comment]
@williambl @MoriyaShiine I'm open to any PRs that would add a way to address this for Fabric. I basically am just doing maintenance-only stuff for my mods now, so it's not likely that I'll get around to this sort of thing myself.

**Comment by SAGESSE-CN** [comment]
> @williambl @MoriyaShiine I'm open to any PRs that would add a way to address this for Fabric. I basically am just doing maintenance-only stuff for my mods now, so it's not likely that I'll get around to this sort of thing myself.

i am very happy to help, just add config?

**Comment by squeek502** [comment]
Not a config. Other mods need to be able to control when AppleSkin's HUD rendering happens, like in https://github.com/squeek502/AppleSkin/issues/94#issuecomment-805342189 but for Fabric. Not sure how Fabric mods typically handle cross-mod interactions like that, though.

**Comment by SAGESSE-CN** [comment]
> Not a config. Other mods need to be able to control when AppleSkin's HUD rendering happens, like in [#94 (comment)](https://github.com/squeek502/AppleSkin/issues/94#issuecomment-805342189) but for Fabric. Not sure how Fabric mods typically handle cross-mod interactions like that, though.

Maybe we could a event bus like forge, other mods could cancel event or change something.

**Comment by williambl** [comment]
A common way for mods to do it in fabric is to create an event, like so:
 https://github.com/williambl/haema/blob/bewitchment/src/main/kotlin/com/williambl/haema/api/BloodDrinkingEvents.kt

**Comment by squeek502** [comment]
Thanks for the info! Some more info here: https://fabricmc.net/wiki/tutorial:events

**Comment by squeek502** [comment]
Ok, I think this has been (finally) fully figured out. Instructions here:

https://github.com/squeek502/AppleSkin/tree/1.16-fabric#for-mod-developers

**Comment by williambl** [comment]
Thanks very much :)
